apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - open-webui
  # - litellm  # DISABLED: supply chain attack in v1.82.7+, re-enable after official all-clear
  - quartz

  - ../../../workloads/gpi
  - ../../../workloads/sillytavern
