apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: open-webui
spec:
  interval: 1h
  values:
    websocket:
      enabled: true
      manager: redis
      url: redis://redis-ha.redis.svc.cluster.local:6379/0
      redis:
        enabled: false
    tika:
      enabled: false
    persistence:
      enabled: false

    service:
      annotations:
        tailscale.com/expose: "true"

    commonEnvVars:
      - name: CHAT_STREAM_RESPONSE_CHUNK_MAX_BUFFER_SIZE
        value: "10485760"
      - name: REPLACE_IMAGE_URLS_IN_CHAT_RESPONSE
        value: "true"
      - name: OFFLINE_MODE
        value: "true"
      - name: ENABLE_OPENAI_API
        value: "true"
      - name: ENABLE_OLLAMA_API
        value: "false"
      - name: ENABLE_ADMIN_EXPORT
        value: "false"
      - name: ENABLE_ADMIN_CHAT_ACCESS
        value: "false"
      - name: BYPASS_ADMIN_ACCESS_CONTROL
        value: "false"
      - name: WEBSOCKET_REDIS_URL
        value: "redis://redis-ha.redis.svc.cluster.local:6379/0"
      - name: VECTOR_DB
        value: "qdrant"
      - name: QDRANT_URI
        value: "http://vector-db-qdrant.ai-infra"

    extraEnvVars:
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: open-webui-db-secret
            key: DATABASE_URL
