apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: marzban-data
  namespace: marzban
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 200Mi
