apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-runner-config
  namespace: forgejo-runner
data:
  config.yaml: |
    log:
      level: info

    runner:
      file: /data/.runner
      capacity: 2
      timeout: 3h
      insecure: false
      fetch_timeout: 5s
      fetch_interval: 2s
      labels:
        - "ubuntu-latest:docker://ghcr.io/catthehacker/ubuntu:act-24.04"
        - "ubuntu-24.04:docker://ghcr.io/catthehacker/ubuntu:act-24.04"
        - "ubuntu-22.04:docker://ghcr.io/catthehacker/ubuntu:act-22.04"
        - "debian:docker://ghcr.io/catthehacker/ubuntu:act-24.04"
        - "self-hosted:docker://ghcr.io/catthehacker/ubuntu:act-24.04"
        - "docker:docker://ghcr.io/catthehacker/ubuntu:act-24.04"
        - "docker-cli:docker://docker:27-cli"

    cache:
      enabled: true
      dir: /data/cache

    container:
      network: host
      privileged: true
      docker_host: "tcp://127.0.0.1:2375"
      workdir_parent: /data/workspace
      valid_volumes:
        - "**"
