apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ghostfolio
  namespace: flux-system
spec:
  interval: 10m
  timeout: 10m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./environments/apps/ghostfolio
  dependsOn:
    - name: cloudnative-pg
    - name: redis-operator
