apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: open-webui-app
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./environments/apps/open-webui/app
  prune: true
  # 明确依赖于基础设施层
  dependsOn:
    - name: open-webui-infra
  decryption:
    provider: sops
    secretRef:
      name: sops-age
