apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sillytavern
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./environments/apps/sillytavern
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
