apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rbac
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/production/rbac
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system-prod
