apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: simple-gemini-git-auth-sync
  namespace: simple-gemini
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-store
    kind: ClusterSecretStore
  target:
    name: simple-gemini-git-auth
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: github-pat-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: image-pull-secret-sync
  namespace: simple-gemini
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-store
    kind: ClusterSecretStore
  target:
    name: image-pull-secret
    creationPolicy: Owner
  template:
    type: kubernetes.io/dockerconfigjson
    data:
      .dockerconfigjson: |
        {
          "auths": {
            "ghcr.io": {
              "username": "{{ .ghcr_username }}",
              "password": "{{ .ghcr_password }}"
            },
            "git.simplelumine.dev": {
              "username": "{{ .forgejo_username }}",
              "password": "{{ .forgejo_token }}"
            }
          }
        }
  dataFrom:
    - extract:
        key: container-registry-secrets
