apiVersion: v1
kind: Secret
metadata:
    name: ghcr-secret
    namespace: simple-gemini
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:QUVrEMyWIRylYx9FgEtDMPGfQVueO4AdkjAbMFRc9hbe2nBijOQMDn6t/pgojjVXRGoiA6/w4KABVSqEEvmG/yQMD7LsLzQy68yqp/hLNSiWdPjg5Ua/0vFR1UViFopYvEFCN//i8qunSQAybj+hNSEsC5KWc8ZF5NRCzWrvndL2OiHMmFRj2sQ94A==,iv:Raq9lclDtwOllREOlaNxI0vPJ6DafwwPEHJ/0dLtWbw=,tag:u6XIs3RE3dSRFtWvl7lVJg==,type:str]
sops:
    age:
        - recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQXBVSllSOWFoTDBTdG9m
            S1NaMElLUE5XbU80V2E1U0ZzbDg5ZGQxR2hjCjZFcUE1ZlkyamZ1MGkvejBWUzVy
            NkE1VTlac0FBSDBWUUlsa0lKZGc3d3cKLS0tIGU2QU9mMVFqU1JoYW96ZVp5S21k
            bHoxRW5iRUFLeCs2aXZPbjZXTGZBeDgKaon4UTg8nUQgWY1HjQL/VwmFlu7XEIJW
            dJS3HOwxvbkY4cUcqeiLvlRYDAiZR3fvxSTDGx1R11CUOJCURyA9jA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T14:03:09Z"
    mac: ENC[AES256_GCM,data:skK/QzmrkIB8/Lzns62pP6SA/GsrB+nNEX7J16skdSQqikaiKj+sPaykBvVHNgenZwDGQnLDpP7hO6FCnoXAFxC37Qi65vLkIGBvrsHm9PXjo2zd42NXRbu5Zthz0IX0cobsqynfRFFbIiMOlTNb9iA46AaFDFoGA3rf55zgPkE=,iv:fsgekR4AWnyLTqWGRwX/wU5JvBDbaSyXZ4wcuqQ1irA=,tag:ozgBIgy4FWuqXspsziCwWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
