apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: simple-gemini-repo
  namespace: simple-gemini
spec:
  interval: 10m
  url: https://github.com/simplelumine/simple-gemini.git
  ref:
    branch: main
