apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: simple-gemini
  namespace: simple-gemini
spec:
  type: oci
  interval: 5m
  url: oci://git.simplelumine.dev/simplelumine
  secretRef:
    name: image-pull-secret
