apiVersion: v1
kind: Secret
metadata:
    name: ghcr-secret
    namespace: simple-gemini
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:i4M8ORZREGXHzZG84yagTrA9+xmC++7xGCCFMbnK6O7Aa432XafcWD5tHw5/1RfelifdKtxY9g36tpdEIHPIP0Mg6INmhjY4kIpiMPM/dv5bUeBUGXkKwF+O/vSb9c85Ta4KVBlMYtIGPEFGBQo9GMebiWW2Ajw7/PGfcAVcTqnJhyWvlntCkwknhA==,iv:sQ0a8zrRXrZESOK1md7rS/dQtC9IZw1TFm7P87p1zHQ=,tag:h/f2f3WxS3dY574x7PXKxg==,type:str]
sops:
    age:
        - recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMjREdWVuZHhZdmZ3T1o4
            U09Va1BRa1F5dHJJV0lZajY2WlBQbW51ckU0Cm5OTjJmZ0Rvd1BtRFZVc0p2YzZS
            OHV4dlAwc1gxN1k0TFFyWE1hYXU1eVkKLS0tIFFnWDloMDRSRHJBRGExRGliekN1
            cFcvZVNsUTVCbVR6MGhFekVnMXNxaWMKZegZH+rQhCFE0gzkXtsu/E21S0YHafLK
            jdE4p4b2gqneKT11yVCag5CuaYqmdBSmWmXLGqxNAY8w5D3H2kK8XA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T13:38:17Z"
    mac: ENC[AES256_GCM,data:9d6ETYD35OeDDvS6yjdbIjjyRj6qsRjkyXX8RWsBHwVnJvjVPmVz6kk+VM2ISoueSuHGpoZ9Yzt+TG/QRSmlPDmPhSHzrPvzLMqTTh0LJNaiuRL0+Tt98qYl1bn/Umo4e/WoLmBbCPFOYwCc/95uagUAqQQWzAWY0xI2kxcDxuU=,iv:oDpnbx0vvec51QMhtFAR89CA23R9fi88h5kNOi/PjUQ=,tag:iT9fUPfA3ODxXNoOI+tzKA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
