apiVersion: v1
kind: Secret
metadata:
    name: simple-gemini-git-auth
    namespace: simple-gemini
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:1mxCRP9Ly1OESzeY,iv:VJ2XtmIxEh+qBecbm2DxlDzoS+jwmXZwmTmh70dtA8g=,tag:7HxcszOrPBC55iYPZg/TAg==,type:str]
    password: ENC[AES256_GCM,data:YNnhArro6V/k4pxrjZccI2twZ+9Aj5gDpUTm7WrnOOFK3uWU0uyQMg==,iv:Oav/Uy59+xc+aQH2BKlHCTa2Kn8rhNCE2rtPfcQwstU=,tag:vS4OI9KMlIfID6R20Ly7Kw==,type:str]
sops:
    age:
        - recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibjQ4dldQTmdycW4wWE5o
            TElPcmk2NThUWlYvU1JITTliTzRMd1NoVkFjCktlMUVCajdMcHRWZXdubzhvSlcv
            VHVVYU9pOWRRaFVibzliN2hYZnRzQUkKLS0tIFdCYlhZY1RJamRDSEhON2YvUy9l
            cHRyMzJsUFcxMFY1YzM2Qkt4T2gvejAKNheLf22fr6PwsZvOgYWBpclXwSHrCKce
            kbkih8Xx57dbLFxpEe+8DfS+bEsej4wfMkxQHPYUnWi1gJTALguzfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T13:56:26Z"
    mac: ENC[AES256_GCM,data:67UPF+wQLF/YySLRqo7/JOFOGGiRD8u5Vkc2QUMhJ9rttmggtVA514NIo4qymXVD+ndw+39IUw/bcJAFux3EMYZoCMI8QQfiux5aMrRz7IArD8PyWc+80L6vbVS59LpUF7mU/vh1+9bSOzwhyjRdGLtuaqgQesgfQ2oV1P1HEoQ=,iv:IGIM4RvXJUsLjdWT8YNWgUfFkeY1B020VKeemNNrxn0=,tag:o2vff/jnwhPaPDeiePXU6g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
