apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actual-budget
  namespace: actual-budget
spec:
  interval: 15m
  chart:
    spec:
      chart: actualbudget
      version: "1.8.3"
      sourceRef:
        kind: HelmRepository
        name: community-charts
        namespace: flux-system
      interval: 15m
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        kubernetes.io/ingress.class: "traefik"
      hosts:
        - host: budget.simplelumine.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: actual-budget-tls
          hosts:
            - budget.simplelumine.com
    persistence:
      enabled: true
      storageClass: "longhorn"
      accessMode: ReadWriteOnce
      size: 100Mi
