apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vm-stack
  namespace: monitoring
spec:
  values:
    grafana:
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - monitor.simplelumine.com
        tls:
          - secretName: grafana-tls
            hosts:
              - monitor.simplelumine.com

      additionalDataSources:
        - name: VictoriaLogs
          type: victoriametrics-logs-datasource
          uid: victoria-logs-datasource
          url: http://vlsingle-victoria-logs-single.monitoring.svc:9428
          access: proxy
          isDefault: false

      plugins:
        - victoriametrics-logs-datasource

      service:
        annotations:
          tailscale.com/expose: "true"
          tailscale.com/hostname: "vm-stack"

      # Inject secret values as Environment Variables
      envFromSecret: vm-stack-auth

      # Configure Grafana.ini to use Env Vars
      grafana.ini:
        server:
          domain: monitor.simplelumine.com
          root_url: https://monitor.simplelumine.com
          serve_from_sub_path: false

        auth.github:
          enabled: true
          allow_sign_up: true
          # Read from Env Vars injected by envFromSecret
          client_id: ${GF_AUTH_GITHUB_CLIENT_ID}
          client_secret: ${GF_AUTH_GITHUB_CLIENT_SECRET}
          scopes: user:email,read:org
          auth_url: https://github.com/login/oauth/authorize
          token_url: https://github.com/login/oauth/access_token
          api_url: https://api.github.com/user
          # Replace with your GitHub Organization
          allowed_organizations: lumine-duality
          # Map GitHub Teams to Grafana Roles
          role_attribute_path: "contains(groups[*], '@lumine-duality/admins') && 'Admin' || 'Viewer'"
