apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus-alias
    app.kubernetes.io/component: monitoring
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vmsingle
    app.kubernetes.io/instance: victoria-metrics
  ports:
    - name: http
      port: 9090
      targetPort: 8428
      protocol: TCP
