---
apiVersion: v1
kind: Service
metadata:
  name: longhorn-frontend-tailscale
  namespace: longhorn-system
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "longhorn-ui"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: longhorn-ui
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
