---
# Longhorn High Availability StorageClass - 3 replicas
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-ha
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
parameters:
  fsType: ext4
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
