apiVersion: v1
kind: Service
metadata:
  name: ghostfolio
  namespace: ghostfolio
  labels:
    app.kubernetes.io/name: ghostfolio
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: ghostfolio
