apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: litellm
  namespace: litellm
spec:
  interval: 1h
  chart:
    spec:
      chart: litellm-helm
      version: "0.1.834"
      sourceRef:
        kind: HelmRepository
        name: litellm
        namespace: litellm
      interval: 1h
  values:
    image:
      # Specific tag required to match Chart version 0.1.834
      tag: v1.80.11-stable.1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 768Mi
