apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cluster.yaml
  - postgres-eso.yaml
  - cluster-vars-eso.yaml
  - postgres-databases.yaml
  - postgres-secret-store.yaml
  - scheduled-backup.yaml

patches:
  - path: postgres-users-patch.yaml
