apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: postgres
spec:
  managed:
    roles:
      - name: open-webui
        ensure: present
        login: true
        passwordSecret:
          name: open-webui-db-secret
      - name: vaultwarden
        ensure: present
        login: true
        passwordSecret:
          name: vaultwarden-db-secret
