apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: open-webui-db
  namespace: postgres
spec:
  cluster:
    name: postgres
  name: open-webui
  owner: open-webui

---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: vaultwarden-db
  namespace: postgres
spec:
  cluster:
    name: postgres
  name: vaultwarden
  owner: vaultwarden

---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: ghostfolio-db
  namespace: postgres
spec:
  cluster:
    name: postgres
  name: ghostfolio
  owner: ghostfolio

---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: vikunja-db
  namespace: postgres
spec:
  cluster:
    name: postgres
  name: vikunja
  owner: vikunja

---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: zitadel-db
  namespace: postgres
spec:
  cluster:
    name: postgres
  name: zitadel
  owner: zitadel
