apiVersion: v1
kind: Secret
metadata:
    name: open-webui-db-secret
    namespace: postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:xOFeaWa28JKeTA==,iv:3I2rjQwQ0hTdkih/gLt9xLHGQggPHtE5uWfpWS4JBeQ=,tag:ALtSo7RXKwsQyRWIGmAobw==,type:str]
    password: ENC[AES256_GCM,data:xr7Um9Wosyi3yhqGPFT1Uw==,iv:j2L1V7E2xLkBt3zAegdVwZtO5Uq4+OCraaHj4vLoZ6o=,tag:/+25s66Pcu1EOH1qXrpXhQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZWZnbTBPVFlVbFdGN0xl
            SklSd1dSelkxV0JaR09HeFF3QlBVbklQdkZNClltcWdGSmt5eUFpbnlDWkMwKzIv
            RnYwYUp4enA2UzZydmt4SDR6ck41aU0KLS0tIEdkb1psU085cTVES2lwMVp5emtp
            Q0RTSVdyVGJGU01HK0xoRllOSHRzbnMKtTCtL4JTNnto3qQnONy24qQ0BJ2JP+b8
            Wfhpz/DYTfRmW5Y9kahCa8q3oGr7oO2KuqLk3GQ4O+T5xWHv1Z7qyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T18:20:14Z"
    mac: ENC[AES256_GCM,data:p+UmhhL00mVE6u9c+6hueBDlWfXEW13xZjmYukPON+rxwLl4PKlwnPat85jCTH6I9XfrjhmCTwXmCi7i0RhxOI6k2FgjmpqIytYNB5WxPQOiZG4GKy9ZjG8FF43G2XigEsED7fYobw4ojW19ZlNaF3L09hFOi7Hsnzw+jBxgbM8=,iv:nAU3oRJhy2NxMjxWe5+Ek20RoYwfjvjcj3qL4lrB1OQ=,tag:RJxP8U08pYEqgsrAPvuudQ==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-db-secret
    namespace: postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:+3PWv7OakRdxqFg=,iv:A4A7t/6wtXZ9gRhJ0vhSoWVmnPAJ6CJRcUPfBmzpMFE=,tag:GUazuIBDJZ12VsFLGQ3RxQ==,type:str]
    password: ENC[AES256_GCM,data:PDSADSDTN7eD7LdcbVqv,iv:Ljnqv4y4umkxiqMiL1CVXi+gUS4HbGwviO44CU8/p1A=,tag:4ntdzZVlhOY9vBUViQ5syQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZWZnbTBPVFlVbFdGN0xl
            SklSd1dSelkxV0JaR09HeFF3QlBVbklQdkZNClltcWdGSmt5eUFpbnlDWkMwKzIv
            RnYwYUp4enA2UzZydmt4SDR6ck41aU0KLS0tIEdkb1psU085cTVES2lwMVp5emtp
            Q0RTSVdyVGJGU01HK0xoRllOSHRzbnMKtTCtL4JTNnto3qQnONy24qQ0BJ2JP+b8
            Wfhpz/DYTfRmW5Y9kahCa8q3oGr7oO2KuqLk3GQ4O+T5xWHv1Z7qyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T18:20:14Z"
    mac: ENC[AES256_GCM,data:p+UmhhL00mVE6u9c+6hueBDlWfXEW13xZjmYukPON+rxwLl4PKlwnPat85jCTH6I9XfrjhmCTwXmCi7i0RhxOI6k2FgjmpqIytYNB5WxPQOiZG4GKy9ZjG8FF43G2XigEsED7fYobw4ojW19ZlNaF3L09hFOi7Hsnzw+jBxgbM8=,iv:nAU3oRJhy2NxMjxWe5+Ek20RoYwfjvjcj3qL4lrB1OQ=,tag:RJxP8U08pYEqgsrAPvuudQ==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: lldap-db-secret
    namespace: postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:G/8s5+c=,iv:ytUiavSeAZu3zjKUCtxSc4NITZPre4f6cQ9qO3b5Kn0=,tag:3M+VNoO0n3YarWzjovSTJw==,type:str]
    password: ENC[AES256_GCM,data:gw1FN+dEN8TEMFvXRcZ0,iv:uq9/7iqnZS1v9kClCHMydOVUd8zChK1UWywTSHc9TI0=,tag:Wp31cumR17I34he6FY3bUw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZWZnbTBPVFlVbFdGN0xl
            SklSd1dSelkxV0JaR09HeFF3QlBVbklQdkZNClltcWdGSmt5eUFpbnlDWkMwKzIv
            RnYwYUp4enA2UzZydmt4SDR6ck41aU0KLS0tIEdkb1psU085cTVES2lwMVp5emtp
            Q0RTSVdyVGJGU01HK0xoRllOSHRzbnMKtTCtL4JTNnto3qQnONy24qQ0BJ2JP+b8
            Wfhpz/DYTfRmW5Y9kahCa8q3oGr7oO2KuqLk3GQ4O+T5xWHv1Z7qyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T18:20:14Z"
    mac: ENC[AES256_GCM,data:p+UmhhL00mVE6u9c+6hueBDlWfXEW13xZjmYukPON+rxwLl4PKlwnPat85jCTH6I9XfrjhmCTwXmCi7i0RhxOI6k2FgjmpqIytYNB5WxPQOiZG4GKy9ZjG8FF43G2XigEsED7fYobw4ojW19ZlNaF3L09hFOi7Hsnzw+jBxgbM8=,iv:nAU3oRJhy2NxMjxWe5+Ek20RoYwfjvjcj3qL4lrB1OQ=,tag:RJxP8U08pYEqgsrAPvuudQ==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: authelia-db-secret
    namespace: postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:H11ESt2CgIU=,iv:FEGzZ1nGVbH/YlcXhJkbxJgjGlSCq2Q0+Srvfa0VKWk=,tag:mFu0nycy+KD6zRyHSKC3Cw==,type:str]
    password: ENC[AES256_GCM,data:j7s34cBxNNIKDhB1R6iiiA==,iv:I1gRBnu3U9MDxT1kBuhnVrrnSmHW1hPC/lzmSwu2tE0=,tag:w6HWRfEu6weY+Ngm9Fk/zQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZWZnbTBPVFlVbFdGN0xl
            SklSd1dSelkxV0JaR09HeFF3QlBVbklQdkZNClltcWdGSmt5eUFpbnlDWkMwKzIv
            RnYwYUp4enA2UzZydmt4SDR6ck41aU0KLS0tIEdkb1psU085cTVES2lwMVp5emtp
            Q0RTSVdyVGJGU01HK0xoRllOSHRzbnMKtTCtL4JTNnto3qQnONy24qQ0BJ2JP+b8
            Wfhpz/DYTfRmW5Y9kahCa8q3oGr7oO2KuqLk3GQ4O+T5xWHv1Z7qyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T18:20:14Z"
    mac: ENC[AES256_GCM,data:p+UmhhL00mVE6u9c+6hueBDlWfXEW13xZjmYukPON+rxwLl4PKlwnPat85jCTH6I9XfrjhmCTwXmCi7i0RhxOI6k2FgjmpqIytYNB5WxPQOiZG4GKy9ZjG8FF43G2XigEsED7fYobw4ojW19ZlNaF3L09hFOi7Hsnzw+jBxgbM8=,iv:nAU3oRJhy2NxMjxWe5+Ek20RoYwfjvjcj3qL4lrB1OQ=,tag:RJxP8U08pYEqgsrAPvuudQ==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: ghostfolio-db-secret
    namespace: postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:hBwCXSMoNmdASQ==,iv:VlBW4OUkcdb1343rIyefwYXMfIoIz4j9SkS7xmKA7/c=,tag:qEv0Sj7uKT+umC7MsQJBIg==,type:str]
    password: ENC[AES256_GCM,data:5ZR9ZPFErHOKp2VoPlxtZB8VteaJJj/t,iv:SVTa8icmG1bBbtZXnlxcpbOvoWhbrt6oHC93771zKks=,tag:BipTGXVb3RVVIY80Z8UjtQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZWZnbTBPVFlVbFdGN0xl
            SklSd1dSelkxV0JaR09HeFF3QlBVbklQdkZNClltcWdGSmt5eUFpbnlDWkMwKzIv
            RnYwYUp4enA2UzZydmt4SDR6ck41aU0KLS0tIEdkb1psU085cTVES2lwMVp5emtp
            Q0RTSVdyVGJGU01HK0xoRllOSHRzbnMKtTCtL4JTNnto3qQnONy24qQ0BJ2JP+b8
            Wfhpz/DYTfRmW5Y9kahCa8q3oGr7oO2KuqLk3GQ4O+T5xWHv1Z7qyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T18:20:14Z"
    mac: ENC[AES256_GCM,data:p+UmhhL00mVE6u9c+6hueBDlWfXEW13xZjmYukPON+rxwLl4PKlwnPat85jCTH6I9XfrjhmCTwXmCi7i0RhxOI6k2FgjmpqIytYNB5WxPQOiZG4GKy9ZjG8FF43G2XigEsED7fYobw4ojW19ZlNaF3L09hFOi7Hsnzw+jBxgbM8=,iv:nAU3oRJhy2NxMjxWe5+Ek20RoYwfjvjcj3qL4lrB1OQ=,tag:RJxP8U08pYEqgsrAPvuudQ==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: vikunja-db-secret
    namespace: postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:ZFtoSq6azw==,iv:f9mfXvA8FnS5eR9J4K8ss2pTWADrEYyKNe1uMAv8pz8=,tag:9+lQxhvFPNOBNnVui1rz1g==,type:str]
    password: ENC[AES256_GCM,data:caugX4bBFcPFmSB5VAAgaH/tLzG1T1pQ,iv:lCxwv/awfZs+TUJiakPvbMUAILqa3KBmq1+4HGFi5Mk=,tag:9OWG2OriNv93ehXQMdIo+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZWZnbTBPVFlVbFdGN0xl
            SklSd1dSelkxV0JaR09HeFF3QlBVbklQdkZNClltcWdGSmt5eUFpbnlDWkMwKzIv
            RnYwYUp4enA2UzZydmt4SDR6ck41aU0KLS0tIEdkb1psU085cTVES2lwMVp5emtp
            Q0RTSVdyVGJGU01HK0xoRllOSHRzbnMKtTCtL4JTNnto3qQnONy24qQ0BJ2JP+b8
            Wfhpz/DYTfRmW5Y9kahCa8q3oGr7oO2KuqLk3GQ4O+T5xWHv1Z7qyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T18:20:14Z"
    mac: ENC[AES256_GCM,data:p+UmhhL00mVE6u9c+6hueBDlWfXEW13xZjmYukPON+rxwLl4PKlwnPat85jCTH6I9XfrjhmCTwXmCi7i0RhxOI6k2FgjmpqIytYNB5WxPQOiZG4GKy9ZjG8FF43G2XigEsED7fYobw4ojW19ZlNaF3L09hFOi7Hsnzw+jBxgbM8=,iv:nAU3oRJhy2NxMjxWe5+Ek20RoYwfjvjcj3qL4lrB1OQ=,tag:RJxP8U08pYEqgsrAPvuudQ==,type:str]
    version: 3.13.3
