apiVersion: v1
kind: Secret
metadata:
    name: postgres-backup-secret
    namespace: postgres
type: Opaque
stringData:
    #ENC[AES256_GCM,data:5exH3bfTaB/A6WiZ0KUXDf7/LwHU9zCCVDTJ2X+DZ8zZBeJFGVGuBbjQuLg=,iv:U+i3yPspB2WqebXNfAPOFwgfsEApJltlFIqy2zLxwRA=,tag:K4GiVesKY3gjue9GZHJphg==,type:comment]
    ACCESS_KEY_ID: ENC[AES256_GCM,data:OcVhvTMDHE4Qe++E3T9Riy9dalPEluTg9rIKoDgV8LA=,iv:nnZ3rsBS0d7LpL+Fz6BJJUtmXGdouz7EDc7FcpaKPkw=,tag:73JOXLCgFVTXaORlu6p+jg==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:0lZNf+MdSo6d9A4xE0HJdMZOSdwntrKroyE+htnLBelO+tmWOxKL4/aGiuL2y1w7OL751WkqvchBHYMaKRrDVA==,iv:zgOYQJVJF/wArS4i8254idNXpJ/OOHopevFpAlMd7fI=,tag:wQwEtp01STxzzcpv3k/0IQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUXZSMFMzaGo3YUJ6c2JD
            L3p2Nnp3anBBMUhZSSswYlQvVFE1L1UvTEFrClZkN3NXMUFOcXdROHdzWkplVVR0
            R0trR1pza01JaXBTekd4UU9IcHowbWsKLS0tIFp6MFVBZndKdHRnN1ZOUVhVR0U5
            REtodkhyTUh3MkpBa2x0TjNWQ2N4REkKLzUdY+9BvCOh9IaxAEJyQUXTmwg6D4NI
            p0A45rGl1hXG0QTz8heFjxJ9FsbP5RrjZnrkF3+q5+RlmbPSYygqAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T10:46:55Z"
    mac: ENC[AES256_GCM,data:kzhtNw0Sv+1sTqWCqfyCzdk5ggOg8eOYKBzQvY6PozIeDqWhIC3caJ+QVYEPdnC0GBD5dy/vEl2453wyEnfa7FNFQIcEKRm5E2Io2Ru2bo0muSqkIdT2yecMbLQQf03vxMHXz+MS10dY/fmNswPig9JB4RZvBuYH2bo3K0OH3To=,iv:UcQqpfE8rRNb1X/qWIvGvFNP8OCd4bn0y0E/TDTvFm8=,tag:k0ZN/g5zOs31o/I5UieKkg==,type:str]
    version: 3.11.0
