apiVersion: v1
kind: Secret
metadata:
    name: cluster-vars
    namespace: flux-system
stringData:
    R2_ENDPOINT_URL: ENC[AES256_GCM,data:5pSPNT26Vti1mLvSreveG7IqEf9YRpZvyiHoh/o+R7GUHuSYYCnqRrR1/28oBmE70d8Kuf95uiod5fEDgUOGDnw=,iv:9HKqdHhwfoY6DVkCT1htnE2Fj384gnTRGOW5TDaKI1w=,tag:Qo0Yt2MYtklp68nLVR8SrA==,type:str]
sops:
    age:
        - recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUEoyYUNESlJ5UzQvZ2Ri
            QnVQNk5UTk9ZWnk1NDlQWTBieXpFMUdHaGpBCmt0elNoOEhIUzJHbEZ1OXI2bDlZ
            UDVMT2NtanF2TXBXRnFHZW93UzUvUjgKLS0tIEM1c3RRRVhha1BocEpyeDRGK1cz
            SERZakFjdUxoaVh1SXJvYWxqZTlOZUEKmBZ9LDzHaYPsiTrkSiMrIqQId75vGZUv
            g8z+eFIXwWe7dRs63nkiv8nF6jyRnI/BPBne1DZzXf47+aNsD7ivlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T17:21:06Z"
    mac: ENC[AES256_GCM,data:+YKn0HZUqrHuVUSlhIC3qJXheNegCSqo/nMM6KT99J8kFmWSj1eAreAL4l8cr796iWhLLrOkqmKkPYVxw7OG1E0ZpwsE8QB4E5fH81U9sQW0KW8JLwfeghvwDKe7g6FrQlVnxD0FpSgU0iqSs9UctYbKcvPECUHJHJVBtzj+Lgg=,iv:ikic7UsOx9rIpcKKUTVNNrekR4BcF6UO5aCs+znsxWc=,tag:UFlqZIOwdWVfChAXj+E9bw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
