apiVersion: v1
kind: Secret
metadata:
    name: open-webui-db-secret
    namespace: postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:gOid5kLfATcqCA==,iv:N+Ha26AKRjwJYHIkr2V5v/1Pf906rUO44Qe2bpHyoiQ=,tag:d90h+Wli8vpK34jxXRvGDw==,type:str]
    password: ENC[AES256_GCM,data:ohNTzwRq1ufhec9YNnpfOg==,iv:unLyB6+ERl6eEjgODZDoQYDEnZn6PLb2OPc8MJCx2xg=,tag:1d1+DM75Sn/t8hcAbRu2ww==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNW45Njh4aUk1Ym9JbkRX
            K3oyd2loZUREY2R4RFVCdGpLcjlLSVNZUlRVCmh6NjczNkVSN2hDcVhBR0ptM3h1
            anVmek9jZ2hPUk5WNEljQTFQYWU5MTQKLS0tIFRvZWhjc3NacXpqMXVhQ3FhcGtz
            Y1paNk5DWFBsM3hOdGF4OVFYdEdOTG8K0yq5IYYWNLVCZQd9jBgsQj6ZSuQhIdQC
            hU9RBTSX/r5uCXD/VmO5bQqSNzpsqHvALParc99rLjoaokS2CmnWDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T19:54:34Z"
    mac: ENC[AES256_GCM,data:e92s0JpqwTAQy6a0xcpiJeTxtY6UtkSAM701Eb6J2xsbMQkuSxtPu/eW3amDvdocbdc7S8Jk4BvlcMiZmGJ125BGckMJ4/e2/lnZur39eCTXoTXy6boaSSxE5GuN5cvC8eC5fxXgvFGrjcpe54/uqg6FUo+YhVCMiAQoIuMTXUQ=,iv:1XBgmetVIp7qzi31gHqjTcUWbiYiCfWDqXe+Phc3VVM=,tag:7VdCx8ip6yWudCqYvVNAhg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-db-secret
    namespace: postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:18Cli8Mh1ye6/2A=,iv:H1ylsxWhVe2adyZWkJtf1JZOc4ixf8HVVuAwuYlmlAs=,tag:JggvGC1CgQS9W7YAas4zag==,type:str]
    password: ENC[AES256_GCM,data:OcrV+Od14eg82/+AxAaH,iv:AFMFMPniFjsZt9SzZLLIQ8wdDqCnCu+BflDG68Lzwb4=,tag:/tnvxxyiIhMUXvYxO/d/iw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNW45Njh4aUk1Ym9JbkRX
            K3oyd2loZUREY2R4RFVCdGpLcjlLSVNZUlRVCmh6NjczNkVSN2hDcVhBR0ptM3h1
            anVmek9jZ2hPUk5WNEljQTFQYWU5MTQKLS0tIFRvZWhjc3NacXpqMXVhQ3FhcGtz
            Y1paNk5DWFBsM3hOdGF4OVFYdEdOTG8K0yq5IYYWNLVCZQd9jBgsQj6ZSuQhIdQC
            hU9RBTSX/r5uCXD/VmO5bQqSNzpsqHvALParc99rLjoaokS2CmnWDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T19:54:34Z"
    mac: ENC[AES256_GCM,data:e92s0JpqwTAQy6a0xcpiJeTxtY6UtkSAM701Eb6J2xsbMQkuSxtPu/eW3amDvdocbdc7S8Jk4BvlcMiZmGJ125BGckMJ4/e2/lnZur39eCTXoTXy6boaSSxE5GuN5cvC8eC5fxXgvFGrjcpe54/uqg6FUo+YhVCMiAQoIuMTXUQ=,iv:1XBgmetVIp7qzi31gHqjTcUWbiYiCfWDqXe+Phc3VVM=,tag:7VdCx8ip6yWudCqYvVNAhg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: lldap-db-secret
    namespace: postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:4ww2qbE=,iv:SR4+XhWveGqbhDusMMFTqqLgI/g1C8i8pqIYAhuRxBk=,tag:irhQOd1dBIjoVDfyqWitGQ==,type:str]
    password: ENC[AES256_GCM,data:uCEI9A/bJmrfqW9ON+1R,iv:5dDcNXyef3xWc9f2/3vJujPxl+0TtyykIoBm7vezry8=,tag:yfsKEJuV+leYeyRGShi3KQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNW45Njh4aUk1Ym9JbkRX
            K3oyd2loZUREY2R4RFVCdGpLcjlLSVNZUlRVCmh6NjczNkVSN2hDcVhBR0ptM3h1
            anVmek9jZ2hPUk5WNEljQTFQYWU5MTQKLS0tIFRvZWhjc3NacXpqMXVhQ3FhcGtz
            Y1paNk5DWFBsM3hOdGF4OVFYdEdOTG8K0yq5IYYWNLVCZQd9jBgsQj6ZSuQhIdQC
            hU9RBTSX/r5uCXD/VmO5bQqSNzpsqHvALParc99rLjoaokS2CmnWDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T19:54:34Z"
    mac: ENC[AES256_GCM,data:e92s0JpqwTAQy6a0xcpiJeTxtY6UtkSAM701Eb6J2xsbMQkuSxtPu/eW3amDvdocbdc7S8Jk4BvlcMiZmGJ125BGckMJ4/e2/lnZur39eCTXoTXy6boaSSxE5GuN5cvC8eC5fxXgvFGrjcpe54/uqg6FUo+YhVCMiAQoIuMTXUQ=,iv:1XBgmetVIp7qzi31gHqjTcUWbiYiCfWDqXe+Phc3VVM=,tag:7VdCx8ip6yWudCqYvVNAhg==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: authelia-db-secret
    namespace: postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:1nHM4Ndv+dM=,iv:mCJO5rkstUTWAp5IJ75hL+IPayy7l9zHAgPaqcVfTW8=,tag:5m8MxQ3TPxwF7l4C71wUuw==,type:str]
    password: ENC[AES256_GCM,data:qtAFQjwRISM4jQQjfxcM6A==,iv:o6jtPbuSB+eZs+CFQRoThp2ormYDA+pMHdXKxTItwpw=,tag:mmsx5vW+2n331JR1UsEN1w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNW45Njh4aUk1Ym9JbkRX
            K3oyd2loZUREY2R4RFVCdGpLcjlLSVNZUlRVCmh6NjczNkVSN2hDcVhBR0ptM3h1
            anVmek9jZ2hPUk5WNEljQTFQYWU5MTQKLS0tIFRvZWhjc3NacXpqMXVhQ3FhcGtz
            Y1paNk5DWFBsM3hOdGF4OVFYdEdOTG8K0yq5IYYWNLVCZQd9jBgsQj6ZSuQhIdQC
            hU9RBTSX/r5uCXD/VmO5bQqSNzpsqHvALParc99rLjoaokS2CmnWDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T19:54:34Z"
    mac: ENC[AES256_GCM,data:e92s0JpqwTAQy6a0xcpiJeTxtY6UtkSAM701Eb6J2xsbMQkuSxtPu/eW3amDvdocbdc7S8Jk4BvlcMiZmGJ125BGckMJ4/e2/lnZur39eCTXoTXy6boaSSxE5GuN5cvC8eC5fxXgvFGrjcpe54/uqg6FUo+YhVCMiAQoIuMTXUQ=,iv:1XBgmetVIp7qzi31gHqjTcUWbiYiCfWDqXe+Phc3VVM=,tag:7VdCx8ip6yWudCqYvVNAhg==,type:str]
    version: 3.13.3
