apiVersion: v1
kind: Secret
metadata:
    name: open-webui-db-secret
    namespace: postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:JEkj8z9dF+wqXg==,iv:YZhOf9oPg1DZUFqzch+Ei93B3d24eiEruhWC4am+Ivs=,tag:ioazrmwVnl88QNd31375UQ==,type:str]
    password: ENC[AES256_GCM,data:m2JdjB92elTS7q3LVDlFKQ==,iv:RUMjT1VCe3PqBTPQ3B7ZaKfCIu0ErC9K0peGmaZ+iNY=,tag:tMjM8Q0+oaMpQcwHjbOgFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSWtaQlg0c1A0Z0lmUDkz
            TUlRWjFCR0NIak1IaW83dllpRCtJZTZEOVRVCmkyWTNadUI5Z1dQQkZjRy9XN1Bz
            SGJZaktLOVljdVF4QVlOMDN0eE9SN2MKLS0tIDBWeVZWQm9nNlZBR0Ntc1NmWFVG
            K1VGdlByVklIdW1nN0dtQ0NSZWcwN0UKzzjE5C3XxiGzDS4sKw5Zv0UTffwk6RuQ
            xQygOk7VDZZ3ZxgkhVYuUWnuA/o8M7csD2u+zE/lCPYj1+QK4DczRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T03:25:05Z"
    mac: ENC[AES256_GCM,data:s9kNT0SDP0FOZmrihiwbNwX+NOagtcZOzWtjuph6JuHVf4XoeR0nJV20N1AzXF5/buh7eoouD2woxnOwUXKJILbDkc5xiOaDQHsiJQA3gRk3Ea6HTWa5dYMoWuHCAICBncY+asgGuoEw4+ygIclIMkqjT3J6Dk0l8hDB+EvsbRc=,iv:qlE/8JGyC7XHmVaBBxPcsTV/wCsS2uQPlnze3ya7KzI=,tag:7ZtZhkx546K9yhAoV79STw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-db-secret
    namespace: postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:1L2xiw79oNFCxpw=,iv:EXMSZayQQftZVnmrqLVjtoHBkTwePpKn6jPrAAU3oM0=,tag:q/PLk9GnoZCSbPMEwmGGVg==,type:str]
    password: ENC[AES256_GCM,data:M3uE+L0XqGOjGHPW5mRD,iv:DQr7b/EYja5K/IcQjUUORvX7ERv4hsw8wv7IWN4/QH8=,tag:mu0Z4RgGZDTsCevSSrnTxA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSWtaQlg0c1A0Z0lmUDkz
            TUlRWjFCR0NIak1IaW83dllpRCtJZTZEOVRVCmkyWTNadUI5Z1dQQkZjRy9XN1Bz
            SGJZaktLOVljdVF4QVlOMDN0eE9SN2MKLS0tIDBWeVZWQm9nNlZBR0Ntc1NmWFVG
            K1VGdlByVklIdW1nN0dtQ0NSZWcwN0UKzzjE5C3XxiGzDS4sKw5Zv0UTffwk6RuQ
            xQygOk7VDZZ3ZxgkhVYuUWnuA/o8M7csD2u+zE/lCPYj1+QK4DczRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T03:25:05Z"
    mac: ENC[AES256_GCM,data:s9kNT0SDP0FOZmrihiwbNwX+NOagtcZOzWtjuph6JuHVf4XoeR0nJV20N1AzXF5/buh7eoouD2woxnOwUXKJILbDkc5xiOaDQHsiJQA3gRk3Ea6HTWa5dYMoWuHCAICBncY+asgGuoEw4+ygIclIMkqjT3J6Dk0l8hDB+EvsbRc=,iv:qlE/8JGyC7XHmVaBBxPcsTV/wCsS2uQPlnze3ya7KzI=,tag:7ZtZhkx546K9yhAoV79STw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: lldap-db-secret
    namespace: postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:DKMjZdU=,iv:FQa7CVNBMJ3+iy+0Oark/X6uR2RAoUZLHisTj6vlqdE=,tag:ImcHe7ZjcGpp2aNs4jm+Lw==,type:str]
    password: ENC[AES256_GCM,data:fzb5ts7AtfB8eKez6XIS,iv:BNC1lVLJfiWd0oDRNEQXOoFQjIgEryDQPYQlMzzbJKE=,tag:7BupeJsqCtP9DmrWoPBHOA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSWtaQlg0c1A0Z0lmUDkz
            TUlRWjFCR0NIak1IaW83dllpRCtJZTZEOVRVCmkyWTNadUI5Z1dQQkZjRy9XN1Bz
            SGJZaktLOVljdVF4QVlOMDN0eE9SN2MKLS0tIDBWeVZWQm9nNlZBR0Ntc1NmWFVG
            K1VGdlByVklIdW1nN0dtQ0NSZWcwN0UKzzjE5C3XxiGzDS4sKw5Zv0UTffwk6RuQ
            xQygOk7VDZZ3ZxgkhVYuUWnuA/o8M7csD2u+zE/lCPYj1+QK4DczRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T03:25:05Z"
    mac: ENC[AES256_GCM,data:s9kNT0SDP0FOZmrihiwbNwX+NOagtcZOzWtjuph6JuHVf4XoeR0nJV20N1AzXF5/buh7eoouD2woxnOwUXKJILbDkc5xiOaDQHsiJQA3gRk3Ea6HTWa5dYMoWuHCAICBncY+asgGuoEw4+ygIclIMkqjT3J6Dk0l8hDB+EvsbRc=,iv:qlE/8JGyC7XHmVaBBxPcsTV/wCsS2uQPlnze3ya7KzI=,tag:7ZtZhkx546K9yhAoV79STw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: authelia-db-secret
    namespace: postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:E1nr/pVGDHg=,iv:koyaG/35KoGigY+xFwaq2Vn0wXtJ7Rff8qjWmG1rpts=,tag:+l9JOkV5nvUI3aMTmD2KnA==,type:str]
    password: ENC[AES256_GCM,data:HCDIxcLP/0rxqWW//RfxHA==,iv:dNFeA8fHJRIIv01f3khrAL7knP/lD1csQBy4jLwXvfA=,tag:9cx4frg91+RF69qDux/quw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSWtaQlg0c1A0Z0lmUDkz
            TUlRWjFCR0NIak1IaW83dllpRCtJZTZEOVRVCmkyWTNadUI5Z1dQQkZjRy9XN1Bz
            SGJZaktLOVljdVF4QVlOMDN0eE9SN2MKLS0tIDBWeVZWQm9nNlZBR0Ntc1NmWFVG
            K1VGdlByVklIdW1nN0dtQ0NSZWcwN0UKzzjE5C3XxiGzDS4sKw5Zv0UTffwk6RuQ
            xQygOk7VDZZ3ZxgkhVYuUWnuA/o8M7csD2u+zE/lCPYj1+QK4DczRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T03:25:05Z"
    mac: ENC[AES256_GCM,data:s9kNT0SDP0FOZmrihiwbNwX+NOagtcZOzWtjuph6JuHVf4XoeR0nJV20N1AzXF5/buh7eoouD2woxnOwUXKJILbDkc5xiOaDQHsiJQA3gRk3Ea6HTWa5dYMoWuHCAICBncY+asgGuoEw4+ygIclIMkqjT3J6Dk0l8hDB+EvsbRc=,iv:qlE/8JGyC7XHmVaBBxPcsTV/wCsS2uQPlnze3ya7KzI=,tag:7ZtZhkx546K9yhAoV79STw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: ghostfolio-db-secret
    namespace: postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:0Uu5xxyjFGBBNw==,iv:GAhoh05wdiHFHh+mRpuhtzdB1tPT0tKx9iiww4zqv2k=,tag:QifZI83hRrVJfOIbYnvfWA==,type:str]
    password: ENC[AES256_GCM,data:FFJvZdvazNKa0oE/Vqc6+HIkg4EurfKy,iv:bKDFEvrPyhHdbaViMdvWmQOIAodO99KUtHjV+OdTY5M=,tag:AEeAgzaVIqmu/NvJrAOmVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSWtaQlg0c1A0Z0lmUDkz
            TUlRWjFCR0NIak1IaW83dllpRCtJZTZEOVRVCmkyWTNadUI5Z1dQQkZjRy9XN1Bz
            SGJZaktLOVljdVF4QVlOMDN0eE9SN2MKLS0tIDBWeVZWQm9nNlZBR0Ntc1NmWFVG
            K1VGdlByVklIdW1nN0dtQ0NSZWcwN0UKzzjE5C3XxiGzDS4sKw5Zv0UTffwk6RuQ
            xQygOk7VDZZ3ZxgkhVYuUWnuA/o8M7csD2u+zE/lCPYj1+QK4DczRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T03:25:05Z"
    mac: ENC[AES256_GCM,data:s9kNT0SDP0FOZmrihiwbNwX+NOagtcZOzWtjuph6JuHVf4XoeR0nJV20N1AzXF5/buh7eoouD2woxnOwUXKJILbDkc5xiOaDQHsiJQA3gRk3Ea6HTWa5dYMoWuHCAICBncY+asgGuoEw4+ygIclIMkqjT3J6Dk0l8hDB+EvsbRc=,iv:qlE/8JGyC7XHmVaBBxPcsTV/wCsS2uQPlnze3ya7KzI=,tag:7ZtZhkx546K9yhAoV79STw==,type:str]
    version: 3.13.3
