apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: shared-cache
  namespace: redis
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.15
    imagePullPolicy: IfNotPresent
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: longhorn
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 500Mi
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
