apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: juicefs-db
  namespace: juicefs
spec:
  instances: 3

  # Use local storage explicitly
  # Ensure your cluster has a StorageClass named 'local-path' or similar
  storage:
    size: 2Gi # Metadata is small
    storageClass: local-path

  bootstrap:
    initdb:
      database: juicefs
      owner: juicefs

  # Postgres Configuration Tuning
  postgresql:
    parameters:
      shared_buffers: "64MB"
      effective_cache_size: "192MB"
      maintenance_work_mem: "32MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1" # SSD optimization
      effective_io_concurrency: "200" # SSD optimization
      work_mem: "4MB"

  # High Availability settings
  primaryUpdateStrategy: unsupervised
