apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: juicefs-csi-driver
  namespace: juicefs
spec:
  values:
    controller:
      replicas: 1
      resources:
        requests:
          cpu: 20m
          memory: 128Mi
    node:
      resources:
        requests:
          cpu: 10m
          memory: 64Mi

    dashboard:
      enabled: true
      service:
        type: ClusterIP
        annotations:
          tailscale.com/expose: "true"
          tailscale.com/hostname: "juicefs"
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
