apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: juicefs-sc
provisioner: csi.juicefs.com
parameters:
  csi.storage.k8s.io/node-publish-secret-name: juicefs-secret
  csi.storage.k8s.io/node-publish-secret-namespace: juicefs
  csi.storage.k8s.io/provisioner-secret-name: juicefs-secret
  csi.storage.k8s.io/provisioner-secret-namespace: juicefs
  csi.storage.k8s.io/controller-expand-secret-name: juicefs-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: juicefs

  pathPattern: "${.PVC.namespace}/${.PVC.name}"

  mountPodRequestCpu: "50m"
  mountPodRequestMemory: "100Mi"
  mountPodLimitCpu: "1000m"
  mountPodLimitMemory: "512Mi"

mountOptions:
  - cache-size=2048
  - buffer-size=64

reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
