apiVersion: v1
kind: Secret
metadata:
    name: open-webui-db-secret
    namespace: postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:yg81md8RQRxJeQ==,iv:NXKA0Mc/cO/F16JTJsLF2UnSXNUFWf6kjmPiWFMyjGA=,tag:fJCK7C6BE6Tzc+j5lGWAEQ==,type:str]
    password: ENC[AES256_GCM,data:/Tcc+cZGy9hP4+ltwbrndQ==,iv:RuJYFsDSE7UO6NQ/QsuEh+OjkcJzeCZcPoGSC4zrAI8=,tag:nfq0icf9blwcZc1LESB/lQ==,type:str]
sops:
    age:
        - recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSWlXWS9UYWpsRXEzRC9M
            ZjlYQTMrQldOOHJzTTdibmJUN3ZxRUJiMEVVCitLdWo1cmtsNmdQT1FNVWFLRjJj
            bHdPbDZqNTVJL3c4K091WVluSzVwbzgKLS0tIFlFa3NWY1QyR2JFZWovaG1nYlQw
            dktjeTE3aTUvdkxuQlJXaDZGak9QUFkKV5PxQMjPZRnN98Mm2EWelJ4BmdduNEKA
            4xYPNYggtj9cz3s0P/PAwwFSmEl8rMBHBTmadXCgyLrTkgk5IGRV6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T04:20:40Z"
    mac: ENC[AES256_GCM,data:aVzEPiXR02ec3/ucOjgfsexkia7wK12Pudt0IO10sA3XTBt/ga5486vHDQi6m7BXvnzgVm2EhB/7rT8NXP5Wh+TlGHKO5YiokrG6FTn3ELos2GXrK1d7acyd44wdtxumiugM1yhb7H8rWj+Z9bfRLSh3oyLYEVpHK5rjYrK4AoI=,iv:KC9NaVGKDeMRBvGDiwTvHHFWzkmJQFOm8hJXRLHEJXc=,tag:E3bTLsy6fqg1onFj/6Rcfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: litellm-db-secret
    namespace: postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:dW0/ZJkwhQ==,iv:5cn7+4swNg9H5g29eOz1VLUzY2o8Pz71fsXqq2vsQLE=,tag:xhocjARh2whdfgoS2EtU2w==,type:str]
    password: ENC[AES256_GCM,data:0rrzbpIlC8bJq/izzH8yMg==,iv:LDbEXKDvZsPoVzfr8BT6R2mO/HrwYNoS9QQggvQWk9M=,tag:+ppRIU0eO5zStaRE4Bhi8g==,type:str]
sops:
    age:
        - recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSWlXWS9UYWpsRXEzRC9M
            ZjlYQTMrQldOOHJzTTdibmJUN3ZxRUJiMEVVCitLdWo1cmtsNmdQT1FNVWFLRjJj
            bHdPbDZqNTVJL3c4K091WVluSzVwbzgKLS0tIFlFa3NWY1QyR2JFZWovaG1nYlQw
            dktjeTE3aTUvdkxuQlJXaDZGak9QUFkKV5PxQMjPZRnN98Mm2EWelJ4BmdduNEKA
            4xYPNYggtj9cz3s0P/PAwwFSmEl8rMBHBTmadXCgyLrTkgk5IGRV6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T04:20:40Z"
    mac: ENC[AES256_GCM,data:aVzEPiXR02ec3/ucOjgfsexkia7wK12Pudt0IO10sA3XTBt/ga5486vHDQi6m7BXvnzgVm2EhB/7rT8NXP5Wh+TlGHKO5YiokrG6FTn3ELos2GXrK1d7acyd44wdtxumiugM1yhb7H8rWj+Z9bfRLSh3oyLYEVpHK5rjYrK4AoI=,iv:KC9NaVGKDeMRBvGDiwTvHHFWzkmJQFOm8hJXRLHEJXc=,tag:E3bTLsy6fqg1onFj/6Rcfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: gatus-db-secret
    namespace: postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:faLqhAM=,iv:imDbYFKp9VOX15veB3cxjCRaBr46FfYCabPCwGt8R5M=,tag:DPmE3Scvx/6EVBfEiUhxEg==,type:str]
    password: ENC[AES256_GCM,data:xfW/oBgVUu3/YPp1gpJ7nw==,iv:I0+R5hSZaT5Dzu1eBRipqdCJuLryG+/uykp57MJgeCc=,tag:1mC7CRGdZACvtmQdeqEjfg==,type:str]
sops:
    age:
        - recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSWlXWS9UYWpsRXEzRC9M
            ZjlYQTMrQldOOHJzTTdibmJUN3ZxRUJiMEVVCitLdWo1cmtsNmdQT1FNVWFLRjJj
            bHdPbDZqNTVJL3c4K091WVluSzVwbzgKLS0tIFlFa3NWY1QyR2JFZWovaG1nYlQw
            dktjeTE3aTUvdkxuQlJXaDZGak9QUFkKV5PxQMjPZRnN98Mm2EWelJ4BmdduNEKA
            4xYPNYggtj9cz3s0P/PAwwFSmEl8rMBHBTmadXCgyLrTkgk5IGRV6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T04:20:40Z"
    mac: ENC[AES256_GCM,data:aVzEPiXR02ec3/ucOjgfsexkia7wK12Pudt0IO10sA3XTBt/ga5486vHDQi6m7BXvnzgVm2EhB/7rT8NXP5Wh+TlGHKO5YiokrG6FTn3ELos2GXrK1d7acyd44wdtxumiugM1yhb7H8rWj+Z9bfRLSh3oyLYEVpHK5rjYrK4AoI=,iv:KC9NaVGKDeMRBvGDiwTvHHFWzkmJQFOm8hJXRLHEJXc=,tag:E3bTLsy6fqg1onFj/6Rcfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: infisical-db-secret
    namespace: postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:2+OyeytS4C9t,iv:znuGLWFeBN/ECRkTNigFzgmE0bH0FyVT4VtYHPkFEb4=,tag:GH34CYToIW88cm1uHEEWFA==,type:str]
    password: ENC[AES256_GCM,data:MoCCALsn2vBLHsQWy9DWOw==,iv:IG0Bm27IfBRtYDS9l8m1GH4qb66TGFPevyJboD6qYV4=,tag:sbt6M0XO+3y9iVY/5D1ueA==,type:str]
sops:
    age:
        - recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSWlXWS9UYWpsRXEzRC9M
            ZjlYQTMrQldOOHJzTTdibmJUN3ZxRUJiMEVVCitLdWo1cmtsNmdQT1FNVWFLRjJj
            bHdPbDZqNTVJL3c4K091WVluSzVwbzgKLS0tIFlFa3NWY1QyR2JFZWovaG1nYlQw
            dktjeTE3aTUvdkxuQlJXaDZGak9QUFkKV5PxQMjPZRnN98Mm2EWelJ4BmdduNEKA
            4xYPNYggtj9cz3s0P/PAwwFSmEl8rMBHBTmadXCgyLrTkgk5IGRV6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T04:20:40Z"
    mac: ENC[AES256_GCM,data:aVzEPiXR02ec3/ucOjgfsexkia7wK12Pudt0IO10sA3XTBt/ga5486vHDQi6m7BXvnzgVm2EhB/7rT8NXP5Wh+TlGHKO5YiokrG6FTn3ELos2GXrK1d7acyd44wdtxumiugM1yhb7H8rWj+Z9bfRLSh3oyLYEVpHK5rjYrK4AoI=,iv:KC9NaVGKDeMRBvGDiwTvHHFWzkmJQFOm8hJXRLHEJXc=,tag:E3bTLsy6fqg1onFj/6Rcfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
