apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qdrant
  namespace: qdrant
spec:
  values:
    # --- HA Configuration ---
    replicaCount: 2

    config:
      cluster:
        enabled: true

    podDisruptionBudget:
      enabled: true
      maxUnavailable: 1

    # --- Security ---
    apiKey:
      valueFrom:
        secretKeyRef:
          name: qdrant-secret
          key: api-key

    # --- Service ---
    service:
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: "qdrant"

    # --- Ingress ---
    ingress:
      enabled: false
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: vector.simplelumine.com
          paths:
            - path: /
              pathType: Prefix
              servicePort: 6333
      tls:
        - secretName: qdrant-tls
          hosts:
            - vector.simplelumine.com
