apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  values:
    nodeSelector:
      node-role.kubernetes.io/control-plane: "true"
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"

    config:
      inCluster: true
      unsafeUseServiceAccountToken: true
      enableHelm: true
      watchPlugins: true
      pluginsDir: "/headlamp/plugins"

    initContainers:
      - name: fetch-flux-plugin
        image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args: ["mkdir -p /headlamp/plugins && cp -r /plugins/* /headlamp/plugins/ 2>/dev/null || true"]
        volumeMounts:
          - name: plugins-dir
            mountPath: /headlamp/plugins

      - name: fetch-cert-manager-plugin
        image: ghcr.io/headlamp-k8s/headlamp-plugin-cert-manager:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args: ["mkdir -p /headlamp/plugins && cp -r /plugins/* /headlamp/plugins/ 2>/dev/null || true"]
        volumeMounts:
          - name: plugins-dir
            mountPath: /headlamp/plugins


    volumeMounts:
      - name: plugins-dir
        mountPath: /headlamp/plugins

    volumes:
      - name: plugins-dir
        emptyDir: {}

    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.middlewares: authelia-authelia-auth@kubernetescrd
      hosts:
        - host: k8s.simplelumine.dev
          paths:
            - path: /
              type: Prefix
      tls:
        - secretName: headlamp-tls
          hosts:
            - k8s.simplelumine.dev

    resources:
      requests:
        cpu: 20m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
