apiVersion: v1
kind: Secret
metadata:
    name: simple-gemini-secrets
    namespace: simple-gemini
type: Opaque
stringData:
    S3_ENDPOINT: ENC[AES256_GCM,data:rq8uJBVHl86gWw7HNrv8GkjeZNkHXSPFC4ZsKzxwPiN5rmb2n3SsAuan4kjNjaqnLn2ENb601bIc3BOuCeCGXd4=,iv:lc3fPWS01uFIFNrCsSIO6pLsgpvbyWoGmQ1XFhS96aA=,tag:2Ecw+CKcxd6IcycsVSQPzw==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:Ts4ju3IqhtK+BxRxG45udnm4,iv:0WIaL9cKLZHCHfRuNsftCJV4RoPjK2DhSwJBW83dFrU=,tag:DY50/h/qr1O92FzVHBvh8g==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:kbsMRFLHaxjKHAMZeeCis0donGAum9D5OfWTvI7eKR0=,iv:Fc/IDk/Vo/pKFzIhJOkuo2L/PhYs1xey5zNa7snJ/ac=,tag:RMdJjfc8mvXQAd7khQGaFQ==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:SyPYQw5E2SC/7cui0j4hWxVZyfnYa1MXwLVYex6lir93EDXZsM4ETjdMDJgHcYVuA2yMLVimgV9nGckyM/PHcg==,iv:aGyLeq9oeCtPRAzaWpxK13DXBU+18muoVSojC/AsZi8=,tag:McfYrS+c9VUXTBZ1rgkF+g==,type:str]
    REDIS_PASSWORD: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVmtOTFh0aVpJUTVsM3FZ
            b0FCSXdiOWkxZWVBV3Z0dU1TN1pOemUvOTBnCk9Kc0RDaGV4Wit3MmxWOGJ0MFpq
            Q2pVc2M2aUNWSHkwMVVDcFJOc2RpNWsKLS0tIEpKTm5jR2JzVGx5S041RTQ4Znho
            WFUwTGN6NWFId00vcE9TL1owNU5QVzAKDf0oNMf1sdTu1/dPT12fCN7HZHK7iSuw
            JtX8Y+ZUgpiWteum+PSsV5Y1wlIrjIvgjj4fjBbq7GlNwZvNrhCMtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T10:46:26Z"
    mac: ENC[AES256_GCM,data:ThYlxh3oWsCB8XNadpMqDbCPBgedNA5etTw09l3z28uS3bWMy50hPzFA/3kYv8j2DZDGV+gY0eCdep11hR1RFLKJlH1LfXdMS7KzlUO2dGrFlEHTCz1HuIeC/TKUnS3qiDgI/DJunPuzhl83h6Ke3QQjataMVB3xV1eOgrHj8uQ=,iv:Xmgv9/YdpKapqtz0t4eI5znMQWOLpi/VwqKby/zKKWU=,tag:bkN8vDIP2Efs+bMyWCiExA==,type:str]
    version: 3.12.2
