apiVersion: v1
kind: Secret
metadata:
    name: simple-gemini-secrets
    namespace: simple-gemini
type: Opaque
stringData:
    S3_ENDPOINT: ENC[AES256_GCM,data:rq8uJBVHl86gWw7HNrv8GkjeZNkHXSPFC4ZsKzxwPiN5rmb2n3SsAuan4kjNjaqnLn2ENb601bIc3BOuCeCGXd4=,iv:lc3fPWS01uFIFNrCsSIO6pLsgpvbyWoGmQ1XFhS96aA=,tag:2Ecw+CKcxd6IcycsVSQPzw==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:Ts4ju3IqhtK+BxRxG45udnm4,iv:0WIaL9cKLZHCHfRuNsftCJV4RoPjK2DhSwJBW83dFrU=,tag:DY50/h/qr1O92FzVHBvh8g==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:q9zSh/3ZhtOimZXOyCYlaZIddeFg8kB2/VWTOtUi7zg=,iv:ZvpD0IIss0yfV1aG73EpnGnj5eJDT7ci0uOMEaHmmto=,tag:7M1GtmPlzt8nIGw3JyAdYQ==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ipdWnGs644UjeYJE+ltCwLkQDPZazgrzI9OYp5lvEMnsf2AKBz9LPfc3HAo5JBOKKR/2uXykZBR9Br8ys65sdQ==,iv:ckn7I3H0YW1evGpzvh0BKzDYJFKtE5D0pGt4HTcOACg=,tag:UqiEVnKdpKzM8YkIo+DgBA==,type:str]
    REDIS_PASSWORD: ""
sops:
    age:
        - recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVmtOTFh0aVpJUTVsM3FZ
            b0FCSXdiOWkxZWVBV3Z0dU1TN1pOemUvOTBnCk9Kc0RDaGV4Wit3MmxWOGJ0MFpq
            Q2pVc2M2aUNWSHkwMVVDcFJOc2RpNWsKLS0tIEpKTm5jR2JzVGx5S041RTQ4Znho
            WFUwTGN6NWFId00vcE9TL1owNU5QVzAKDf0oNMf1sdTu1/dPT12fCN7HZHK7iSuw
            JtX8Y+ZUgpiWteum+PSsV5Y1wlIrjIvgjj4fjBbq7GlNwZvNrhCMtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T13:38:58Z"
    mac: ENC[AES256_GCM,data:9jP0nUmrxvLUtI9983tQaZckkq8yTUr1qVN8laf5jno4oF7/FBrb7Wqqv7VeHk/IbIDo/0Hsq0X4Aem5kz+8cbIX3NDVB1kAYZuQmom1cd094xjyi5OxRlqrJWIdY3r/ZsvPVMod3HXkWqjJNXbN+aeFtB/tUyPzjG4ptkCEzBA=,iv:vUkOE3usgbxxQNFasxcy5vK0H1vdeq14aIk7qXZB4O8=,tag:hTj1kmvRlILtWY+a2p9r9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
