apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secret
    namespace: vikunja
type: Opaque
stringData:
    s3-endpoint-url: ENC[AES256_GCM,data:OlrwVCfqxSPNX1Evm/kvM/32FIwfzHLtLmzpoDp8uKnfX9Oitd+n9eai3iddde2H53b5YddXfEmwxRxC5MBLCt0=,iv:u2wz3HpVQFSJTLLdp4MbQRgLnqCME8PZ/07x3wRHPpg=,tag:nWBE2IYCahWTLF0VkIDYCA==,type:str]
    s3-access-key-id: ENC[AES256_GCM,data:HCc11FS4bIB0p4zAOm+K4kqEX9+RGJ/6C5loH/SZu2s=,iv:kvrgMBCXOM/CCuOhgUn8sP+5AHhfovbo3RfTPJv77nw=,tag:Cv7qp7gJutGffMbURZcicA==,type:str]
    s3-secret-access-key: ENC[AES256_GCM,data:edSmLEDjlE27cAalyJA66gozLTnBXvjLTACyK7D5hLdZSS/J12jvFTSOCTgXNb858eOh+NMVbvOL5TKGyEEr1w==,iv:hRUyy4ddlWHkgZ8Tw8wagsL1drYPVPBTsq8z1S+abtA=,tag:O8wHvWv5u0TILS1w743m3A==,type:str]
    oauth-client-secret: ENC[AES256_GCM,data:s780olFXqGwb5cSW8AadB+0lRQTIeEv//EuTn6EIZpJcOwf6LEGZI2cLyDg/sLrmsKxoYXdh62Qlo9pu5ZLAcg==,iv:jYFkstK0aD92mu2GFfsHaMP0zq9ncCqMpuqUV5qsqcQ=,tag:q6uKpZ4fkNIA5IYs4IYVhg==,type:str]
    smtp-password: ENC[AES256_GCM,data:kcwdoM7f8pLaf8P/sRzheeA1Js671CevcnLamqJYfq6vgQ3/,iv:ptMDE3Tf4JKUhUwLWEBtZyDTD6dxsXcrcdSOdCMO5A4=,tag:Ux0e47oa9DmYWzVGZpSc7A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYyswUGkwaUg0RFgzMUFY
            ZDBVZ0ZPWDdPM2cwVnhhdVM2eUlqSFpFZlM4CkN2UXE0b3VlblA3dWVaNEZXenRa
            R2dsMEVKSEpqUi81WVN6MG51cDh3T28KLS0tIEpUMGpxRWpnSEM1L1dOSWlLcFp6
            Q1R0RE4xUjk4SE5BTzR1OEwxdENaSEkKgSbVQp8RQKSSC6iojS/Nh6PQBbxt/bHT
            yQyLr56ejNz6VffA+6nzyqFqqm7sk00UuU2vJBoIY4VPcXXFAGVJiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T13:53:05Z"
    mac: ENC[AES256_GCM,data:34rqi//lExeI4HexYqE+cS1VTv9yOcElHJTRAEeBbFjhPXnlmUDlciOeeZYVwyDK90bLHGTP2ifBVlBERiLP6aI1NnzK3hZ5RmvLxkXbaj2XNQ8y7I7bQ49vie9YDOimCr8fPST8Irk50iCJYMtBxoyeF0oa9uRYLaoMrcN6u9Y=,iv:yr+qfN47ERidsg8bpVxnIYxAHBRF6Pfffogq0Solt7w=,tag:mC0wGTeXjXOvQthR1Vt1wQ==,type:str]
    version: 3.13.3
