apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secret
    namespace: vikunja
type: Opaque
stringData:
    s3-endpoint-url: ENC[AES256_GCM,data:OlrwVCfqxSPNX1Evm/kvM/32FIwfzHLtLmzpoDp8uKnfX9Oitd+n9eai3iddde2H53b5YddXfEmwxRxC5MBLCt0=,iv:u2wz3HpVQFSJTLLdp4MbQRgLnqCME8PZ/07x3wRHPpg=,tag:nWBE2IYCahWTLF0VkIDYCA==,type:str]
    s3-access-key-id: ENC[AES256_GCM,data:HCc11FS4bIB0p4zAOm+K4kqEX9+RGJ/6C5loH/SZu2s=,iv:kvrgMBCXOM/CCuOhgUn8sP+5AHhfovbo3RfTPJv77nw=,tag:Cv7qp7gJutGffMbURZcicA==,type:str]
    s3-secret-access-key: ENC[AES256_GCM,data:edSmLEDjlE27cAalyJA66gozLTnBXvjLTACyK7D5hLdZSS/J12jvFTSOCTgXNb858eOh+NMVbvOL5TKGyEEr1w==,iv:hRUyy4ddlWHkgZ8Tw8wagsL1drYPVPBTsq8z1S+abtA=,tag:O8wHvWv5u0TILS1w743m3A==,type:str]
    oauth-client-secret: ENC[AES256_GCM,data:Q/IE/36qPHVBFRQyFba9NSG5CqT4U+wup8TpJLvH6BS8RHRJ55oT8vTNqRy1eU4H,iv:0DvcXDvt4BSmLk09SUU37JbpOAeeT/xpSR326sYw2B4=,tag:Ltyzby2kM4huqesO9w2wCw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYyswUGkwaUg0RFgzMUFY
            ZDBVZ0ZPWDdPM2cwVnhhdVM2eUlqSFpFZlM4CkN2UXE0b3VlblA3dWVaNEZXenRa
            R2dsMEVKSEpqUi81WVN6MG51cDh3T28KLS0tIEpUMGpxRWpnSEM1L1dOSWlLcFp6
            Q1R0RE4xUjk4SE5BTzR1OEwxdENaSEkKgSbVQp8RQKSSC6iojS/Nh6PQBbxt/bHT
            yQyLr56ejNz6VffA+6nzyqFqqm7sk00UuU2vJBoIY4VPcXXFAGVJiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T18:17:08Z"
    mac: ENC[AES256_GCM,data:Ia18WSnff/zcJQKvGzG8r/QbS+330EaxMW76f/aRlFpujDI420sovQ8XSfKHc6S2Zfqpk/glK8KLvHzJccVOKGeOaAn0QRyPItHqj98mATN/a2ZoKSbvcVH5A+S+HXsqOVz5DVJX+tPgQnkUk5xvOkYUIRd73JrTQEbAAFNAsWM=,iv:wJJcgkM2nPRVpqiZ7fgkIKz1XmzXqmc9Nhq0BQlf5mY=,tag:sBKrudTsdBGnQI4s3EsOYw==,type:str]
    version: 3.13.3
