apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../system/lldap
  - ingress.yaml
  - lldap-secrets.sops.yaml
  - lldap-eso.yaml

patches:
  - path: lldap-patch.yaml
