apiVersion: apps/v1
kind: Deployment
metadata:
  name: lldap
  namespace: lldap
spec:
  template:
    spec:
      containers:
        - name: lldap
          envFrom:
            - secretRef:
                name: lldap-secrets
          env:
            - name: LLDAP_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: lldap-db-secret
                  key: LLDAP_DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: lldap
  namespace: lldap
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "lldap"
