apiVersion: v1
kind: Secret
metadata:
    name: lldap-secrets
    namespace: lldap
type: Opaque
stringData:
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:898X1sCUX5fDq3ehbr79YVZzx8de587cE52CZFL+5S3jVoWP5kc3VrrkDy+jDvC7BOAfKUuGgKl0321M19qSiQ==,iv:nkPtPA6WiM/BLMBgPZ9nADgWWxZg1bwBxTekY64z13g=,tag:srGCfMlqfIKauZHPn31XVw==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:NQ8MCdv6EkHb4eUR/JCwqgb96ghi+TcmzfsKIjyT9kU=,iv:wm0Sy1f8z4kaKWwffvuygxoG1FaYzCCUmYRkpA7RSH8=,tag:ZGwz8+XPEbevfIPcRzZF5w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWVp4cndOSVVNZjZDdVZ5
            OEJiS2daNjUrb2Yxd1NVUlgwVzBWSzJQbHpVCmtZM3RIeWJiSHJkd3I3OGd5Vmhm
            Y2pxQzNTdjNoT0NlVDZjREY2WDg0UGsKLS0tIC9qSjNNdGkwSzBCNmVUVnlMd0Rt
            Vk9STHJoS1N4aStHdnA4WENPcitWdWcKEAX+stzeC3lHJHHC2907ii+Kb52Y+mCK
            EgDpcEVsYgGCXobXYPQVzs3ZUYaL7trJ+cZqzC8s+X8q4L8lEeuLrA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T19:51:33Z"
    mac: ENC[AES256_GCM,data:84u/g0gWt0/Es9Cav9HJL41cAsI0RoiWm+IiFE7GxvdPfSCzoIFGJiatffu/s7ywCJf5KeY1f+9vkbkKFrrLnCDAVTeQ2lmF+U7EO2upvTPGBm6tLe6Ua4DMGfroBARwIHx8BsgQEL5ivzYIYmc62WlTZNLaDQdVlBvoBpzc0Cs=,iv:OfYHTY3IsuAykMdC0v6q65z0ao/VSgy9fN1iEczkjaA=,tag:75Tot1nZvUE804XjxmhIvg==,type:str]
    version: 3.13.3
