apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: flux-system
spec:
  values:
    trivy:
      ignoreUnfixed: true
      mode: ClientServer
      resources:
        requests:
          cpu: 20m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 512Mi
    trivyOperator:
      scanJobTolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
    operator:
      builtInTrivyServer: true
      scanJobsConcurrentLimit: 1
      vulnerabilityScannerScanOnlyCurrentRevisions: true
      resources:
        requests:
          cpu: 20m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 256Mi
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
