apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
  namespace: victoria-logs
spec:
  interval: 1h
  chart:
    spec:
      chart: victoria-logs-single
      version: "0.11.24"
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: victoria-logs
      interval: 1h
  values:
    server:
      retentionPeriod: 7d
      persistentVolume:
        enabled: true
        storageClassName: local-path
        size: 20Gi
        accessModes:
          - ReadWriteOnce
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
