apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
  namespace: victoria-logs
spec:
  interval: 1h
  chart:
    spec:
      chart: victoria-logs-single
      version: "0.11.24"
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: victoria-logs
      interval: 1h
  values:
    server:
      retentionPeriod: 1M
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 1Gi
