apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secrets
    namespace: oauth2-proxy
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:iglTBQDs+qmOqeL5dTrI0UPL,iv:yQrCDDZsW2IJxoQkLlpBLQA4KipRRvwEGuq4NwyrZAI=,tag:xqOK2sUr3dWL1TecRMYq+w==,type:str]
    client-secret: ENC[AES256_GCM,data:Ne1EF3M+C2N5GlZWeXZx8gTL9dYlQp58CHftYnzcOZlQunobRG7Zwl55LanDoSa7DOc2lTr68iRRozLVhvL+gw==,iv:KgOoXS02uUFHPXeTqEi8zo7wfl4pRHbt8d6l01AKegI=,tag:VryZ2IFNz659YaXnjkhXPA==,type:str]
    cookie-secret: ENC[AES256_GCM,data:HqLlPFyuXbqwC9kiQnF/QYKoTepJYJd77W2lhGv+sB7kRHRg6oEoKWR471Y=,iv:3HNydztw0kUKaPPHdnn07Jhm6ynOezgk1PW1iiF7N08=,tag:JwgP6uTqaDznqVuPlN2t3A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwT01PdkVUNlBhWmlWRFg5
            eXF2Nk1iNHhab1JzYVFSekZ6a0NLYUpPUmtnCnhoSHJaSWVZQjMzZjlPYlA2TEhq
            aFhMOGJ6UEp6aTFOMDBHMWhRQmRZMWsKLS0tIGtlNDZEK3R4alM0TWFHQWYwRzAy
            aXRYTjJwZGN1d0ZXUlQ3TUVRd09oeWcKOsI12MZQHkdsLnCAuKsXlX4ECL95vwBf
            FaxiDzKuIeg4RdPdOxSY6XTc2fZYPksMpirVzPuUOXFcJvAJ9PMRGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T17:08:48Z"
    mac: ENC[AES256_GCM,data:WcfXz1N1CTqdcnvkXJPWW8gGu4IS7NxpdgiAMfJprR9UiKTHQ57XNNWKANHxr0v8Oy13fMZVR8TE7/q7qwqdhuKnTG38LkhPwLoO3RltvVyDIZbx5uaSPz8maxJWbppXfdGgbV4fJybJ5CtC6lYaHSIgEoVjTqPvQ6xXkcRdLS4=,iv:793kYl0uTyGnF8BbPjJ3O6TuJnHBZsEUa2hwcqifdUg=,tag:PyqUR2LfSjvdzgATSaWJCw==,type:str]
    version: 3.13.3
