apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder
  namespace: coder
spec:
  interval: 1h
  chart:
    spec:
      chart: coder
      version: "2.30.x"
      sourceRef:
        kind: HelmRepository
        name: coder
        namespace: coder
      interval: 1h
  values:
    coder:
      # Minimal defaults for base installation
      env: []
    postgres:
      # Embedded postgres enabled by default for base to work standalone
      enabled: true
      persistence:
        enabled: true
        size: 10Gi
