apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../platform/coder
  - coder-eso.yaml
patches:
  - path: coder-patch.yaml
    target:
      kind: HelmRelease
      name: coder
