---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: redis-operator
  namespace: ot-operators
spec:
  interval: 24h
  url: https://ot-container-kit.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-operator
  namespace: ot-operators
spec:
  interval: 30m
  chart:
    spec:
      chart: redis-operator
      version: 0.22.1
      sourceRef:
        kind: HelmRepository
        name: redis-operator
        namespace: ot-operators
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
