apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  interval: 1h
  chart:
    spec:
      chart: gitea
      version: 12.x
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: gitea
  values: {}
