apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infisical
  namespace: infisical
spec:
  interval: 1h
  chart:
    spec:
      chart: infisical-standalone
      version: "1.7.2"
      sourceRef:
        kind: HelmRepository
        name: infisical
        namespace: infisical
      interval: 1h
  values:
    infisical:
      # Prerequisites:
      # - Kubernetes Secret named 'infisical-secrets' in the same namespace
      # - PostgreSQL database (controlled by postgresql.enabled or external DB_CONNECTION_URI)
      # - Redis instance (controlled by redis.enabled or external REDIS_URL)
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
    postgresql:
      # Database name: infisicalDB | User: infisical | Password: root (default)
      enabled: true
    redis:
      enabled: true
    ingress:
      enabled: false
      nginx:
        enabled: false
