apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infisical
  namespace: infisical
spec:
  interval: 1h
  chart:
    spec:
      chart: infisical-standalone
      version: "1.7.2"
      sourceRef:
        kind: HelmRepository
        name: infisical
        namespace: infisical
      interval: 1h
  values:
    # Add custom values here if needed
    # fullnameOverride: "infisical"
