apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  dependsOn:
    - name: services
  interval: 10m
  path: ./clusters/production/overlays/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system-prod
  decryption:
    provider: sops
    secretRef:
      name: sops-age
