apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system-prod
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/simplelumine/k8s-gitops
  ref:
    branch: main
