apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/production/overlays/system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system-prod
  decryption:
    provider: sops
    secretRef:
      name: sops-age
