apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: workloads
  namespace: flux-system
spec:
  dependsOn:
    - name: platform
    - name: datastores
  interval: 10m
  path: ./clusters/production/overlays/workloads
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system-prod
  decryption:
    provider: sops
    secretRef:
      name: sops-age
