apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moe-atelier-ingress
  namespace: moe-atelier
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - moe.genshinnb.textverse.space
      secretName: moe-atelier-tls
  rules:
    - host: moe.genshinnb.textverse.space
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: moe-atelier
                port:
                  number: 5173
