apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/spartan114514/moe-atelier
    newName: ghcr.io/FSHebe233/moe-atelier
    newTag: sha-6feaeda
