apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moe-atelier-data
  namespace: moe-atelier
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
