apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vm-stack
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: "0.66.x"
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: monitoring
  values:
    # Global config
    global:
      clusterLabel: cluster

    # Disable single-node to use cluster mode
    vmsingle:
      enabled: false

    # Enable Cluster mode for HA (application-replication)
    vmcluster:
      enabled: true
      spec:
        retentionPeriod: "10d"
        replicationFactor: 2
        vmstorage:
          replicaCount: 2
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              memory: "1Gi"
          storage:
            volumeClaimTemplate:
              spec:
                storageClassName: local-path
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 20Gi
        vmselect:
          replicaCount: 1
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              memory: "512Mi"
        vminsert:
          replicaCount: 1
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              memory: "512Mi"

    # Configure Grafana with VictoriaLogs integration
    grafana:
      enabled: true
      persistence:
        enabled: false
      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard
        datasources:
          enabled: true
          label: grafana_datasource

    # standard components
    vmalert:
      enabled: true
    vmagent:
      enabled: true
    victoria-metrics-operator:
      enabled: true
