apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zitadel
  namespace: zitadel
spec:
  interval: 1h
  chart:
    spec:
      chart: zitadel
      version: "10.0.4"
      sourceRef:
        kind: HelmRepository
        name: zitadel
        namespace: zitadel
  values: {}
