apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gpi-creds
  namespace: gpi
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: juicefs-sc
  resources:
    requests:
      storage: 200Mi
