apiVersion: v1
kind: Secret
metadata:
    name: cilium-secret
    namespace: kube-system
stringData:
    values.yaml: ENC[AES256_GCM,data:LD+DBPEXvhZZiIru8jT96SLnHaUPCsWjXb+FEbhLkHzhPKt65Nd2IVPDpFIgQ+BIPw==,iv:9TPnDACpfYyHDiZP+LcXio4KvbOZNv1nBKa97vPO0LQ=,tag:oyDBJu2fx9z0X8270HZ2vg==,type:str]
sops:
    age:
        - recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaM0M5RUpmVFdsaUllQUVO
            d2JBQmF1bGgyVnVCRWJOY3hBcEZ3R0xJUWtnClI4MmR1Qm1uN05odXhYVklIYWhz
            OHZnSzBpYWJDTUtCY01leSthemIxQncKLS0tIHVxMnRVUFZNYTNuandmejBvdFBN
            MXpIVXJWNTkyT2RyOHI0VzMvdHVrUUEK+RndQwiqvR2OiDe4mnsMZEWW/naMBICM
            xSBqPVmkw5cE6iHwoFB0/Z4Iy0WVshCNuoDvZ8paOKQf9LFJXCOO8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T15:05:02Z"
    mac: ENC[AES256_GCM,data:aOJIqI5z5W5364aa/fS3YtmX5edJqQnmiSYFdd4jJHbYNI/tqfqJCAsvb5CpZppVeZooOTGWiX10r1f2AzcUjaXfrykFmtxDxBi0AaEvWJK+k9eLv37J/d+xiu0nRUtJ2TT0DO8oLD2t42MTFmjXPb7xeOPhJ4GKGq8IPOMDWic=,iv:adYWyzt5S6YaBMwADqOIROMGY2vxXp+DN85rkcj5nsw=,tag:5HlFcTOFnRvxUKjN1xXZvw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
