apiVersion: v1
kind: Secret
metadata:
    name: cilium-secret
    namespace: kube-system
stringData:
    values.yaml: ENC[AES256_GCM,data:0IhIQk1xF63h/gwO+qSBJBh4tLxWDtju/HAAiGZ4cAIdlVVrkzHweRxBUEDQNB3G2bk=,iv:nfEbwPWuFXheSDn4CmOL9pihTPoFLEK7Z4znZT9ciFw=,tag:3YlGJnEsiZjrwu2g1ItBfQ==,type:str]
sops:
    age:
        - recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBR1o3ejNLUGd1UU13Qkla
            akEydHVObkxZbVoyOTQxWnA0VG91REdNQjB3Cm9sR0ticEtiMHI0eUN0UERsTVdT
            cnNmRVpjWlVJdDc2NWRrdkxjaFNCcHMKLS0tIFpqNFdEeHVoZlJKVFY2WWs5TWht
            dTVCdXFDajdZU2lDc1dTMjFkOWQzQUEK60XN/VOlxYw0trP+0ri8o2lthUIvShBC
            AgFyL4dTmDWagGqS7RdiM+ZeCJsVS26297zCvB0f7S4a3f+zAk3mVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T15:28:21Z"
    mac: ENC[AES256_GCM,data:N7x2KXuPKRwY7gd/5Sq113YvK1Q55lqJz67tP3vIhsAhpenQ5BsdiK7rPFeR0waH/WQnYRUmoIwiuYuLmAP9U1nh6RmIuM5cMGY35I2U08I9MOMB28czvWswTWkW679LEx22bKbHijr2bU5KfzivBcGPMT5Qi/FsRPrntxyBtIQ=,iv:dotPruHpvc9n7bcm3QrCOSJoVPZ/mia4cNyExLiYINE=,tag:1uv0Xd4QSpi70LDZpdvqgQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
