apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: open-webui
  namespace: open-webui
spec:
  interval: 5m
  chart:
    spec:
      chart: open-webui
      version: 8.12.2
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: flux-system
      interval: 1m
  values:
    ingress:
      enabled: true
      className: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
      hosts:
        - host: "chat.simplelumine.com" # <--- 请替换为您的域名
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: open-webui-tls
          hosts:
            - "chat.simplelumine.com" # <--- 请替换为您的域名

    # 禁用内置的 Ollama
    ollama:
      enabled: false

    # 启用 Websocket 并禁用内置的 Redis
    websocket:
      enabled: true
      redis:
        enabled: false

    # 从 Secret 动态获取数据库连接信息，避免硬编码密码
    extraEnvVars:
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: open-webui-db-app
            key: dsn
      - name: REDIS_URL
        value: "redis://open-webui-cache-master.open-webui.svc.cluster.local:6379"
