apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
  namespace: gatus
spec:
  interval: 1h
  chart:
    spec:
      chart: gatus
      version: 1.4.5
      sourceRef:
        kind: HelmRepository
        name: gatus
        namespace: gatus
  values:
    service:
      type: ClusterIP
    persistence:
      enabled: false
    serviceMonitor:
      enabled: false
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 32Mi
    securityContext:
      capabilities:
        add:
          - NET_RAW
