apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: garage
  namespace: garage
spec:
  interval: 1h
  url: https://git.deuxfleurs.fr/Deuxfleurs/garage.git
  ref:
    tag: v2.1.0
