apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-tempo
  namespace: monitoring
spec:
  values:
    # Prefer lite tier nodes for trace storage
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/tier
                  operator: In
                  values:
                    - flash
