apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-tempo
  namespace: monitoring
spec:
  values:
    nodeSelector:
      node-role.kubernetes.io/non-critical: "true"
    tolerations:
      - key: "node-role.kubernetes.io/non-critical"
        operator: "Exists"
        effect: "NoSchedule"
