apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: xray
  namespace: xray
spec:
  values:
    reality:
      sni: "www.usc.edu"
      dest: "www.usc.edu:443"
      serverNames:
        - "www.usc.edu"
    nodes:
      - name: sfo-wk-01
      - name: lax-wk-01
      - name: lax-wk-02
      - name: slc-cp-01
