apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infisical
  namespace: infisical
spec:
  values:
    infisical:
      # Reference the secret containing ENCRYPTION_KEY, AUTH_SECRET, and REDIS_URL
      kubeSecretRef: "infisical-secrets"
      
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
      replicaCount: 1

      service:
        annotations:
          tailscale.com/expose: "true"
          tailscale.com/hostname: "infisical"

    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hostName: "vault.simplelumine.com"
      tls:
        - secretName: infisical-tls
          hosts:
            - vault.simplelumine.com
      nginx:
        enabled: false

    # Disable in-cluster databases
    postgresql:
      enabled: false

    redis:
      enabled: false
