apiVersion: operator.victoriametrics.com/v1
kind: VLSingle
metadata:
  name: victoria-logs-single
  namespace: monitoring
spec:
  # Prefer lite tier nodes for log storage
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/tier
                operator: In
                values:
                  - flash
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs-collector
  namespace: monitoring
spec:
  values: {}