apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-staging
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./environments/apps/overlays/staging
  prune: true
  # 等待 core 组件部署完成
  dependsOn:
    - name: core-staging
