apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../platform/outline
  - outline-eso.yaml
  - ingress.yaml

patches:
  - path: outline-patch.yaml
    target:
      kind: Deployment
      name: outline
