apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store
spec:
  provider:
    kubernetes:
      # Use the controller's pod identity (ServiceAccount) to access secrets
      # This requires the controller to have cluster-wide RBAC permissions to read Secrets
      auth:
        serviceAccount:
          name: "" # implies using the controller's SA
      server:
        url: "https://kubernetes.default.svc"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
