apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-store
spec:
  provider:
    gcpsm:
      projectID: "root-beanbag-506813-v5"
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-secret-manager-creds
            key: secret-access-credentials
            namespace: external-secrets
