apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder
  namespace: coder
spec:
  values:
    coder:
      env:
        - name: CODER_PG_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: coder-db-url
              key: url
        - name: CODER_OAUTH2_GITHUB_DEFAULT_PROVIDER_ENABLE
          value: "false"
        - name: CODER_ACCESS_URL
          value: "https://code.simplelumine.com"
        # GitHub OAuth
        - name: CODER_OAUTH2_GITHUB_ALLOW_SIGNUPS
          value: "true"
        - name: CODER_OAUTH2_GITHUB_ALLOWED_ORGS
          value: "lumine-duality"
        - name: CODER_OAUTH2_GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: coder-oauth
              key: client-id
        - name: CODER_OAUTH2_GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: coder-oauth
              key: client-secret
      ingress:
        enable: true
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        host: code.simplelumine.com
        tls:
          enable: true
          secretName: coder-tls
      service:
        annotations:
          tailscale.com/expose: "true"
          tailscale.com/hostname: "coder"
    postgres:
      enabled: false
      persistence:
        enabled: false
