apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
  namespace: gatus
spec:
  values:
    config:
      endpoints:
        # --- External Connectivity ---
        - name: open-webui
          group: external
          url: "https://chat.simplelumine.com"
          interval: 2m
          conditions:
            - "[STATUS] == 200"
        - name: grafana
          group: external
          url: "https://monitor.simplelumine.com"
          interval: 2m
          conditions:
            - "[STATUS] == 200"

        # --- Internal Services ---
        - name: open-webui-svc
          group: internal-services
          url: "http://open-webui.open-webui.svc.cluster.local:80"
          interval: 30s
          conditions:
            - "[STATUS] == 200"
        - name: vm-stack-svc
          group: internal-services
          url: "http://vmselect-vm-stack-victoria-metrics-k8s-stack.monitoring.svc.cluster.local:8481/select/0/prometheus/api/v1/query?query=up"
          interval: 30s
          conditions:
            - "[STATUS] == 200"
