apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 1h
  valuesFrom:
    - kind: Secret
      name: cilium-secret
      valuesKey: values.yaml
  values:
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
