apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-operator-oauth-sync
  namespace: tailscale
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-store
    kind: ClusterSecretStore
  target:
    name: tailscale-operator-oauth
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: tailscale-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-cloudflare-sync
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-store
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: cloudflare-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-cloudflare-sync
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-store
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: cloudflare-secrets
