apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Tailscale
  - ../../../../system/tailscale-operator
  
  # Cert Manager
  - ../../../../system/cert-manager
  
  # External DNS
  - ../../../../system/external-dns

  # ESO Secrets Sync
  - connectivity-eso.yaml

