apiVersion: v1
kind: Pod
metadata:
  name: forgejo-restore-helper
  namespace: forgejo
spec:
  nodeSelector:
    kubernetes.io/hostname: lax-wk-01
  containers:
    - name: helper
      image: alpine:latest
      command: ["sleep", "3600"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: gitea-shared-storage
