apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qdrant
  namespace: qdrant
spec:
  interval: 1h
  chart:
    spec:
      chart: qdrant
      version: "1.16.3"
      sourceRef:
        kind: HelmRepository
        name: qdrant
        namespace: qdrant
  values: {}
