apiVersion: v1
kind: Secret
metadata:
    name: qdrant-secret
    namespace: qdrant
stringData:
    api-key: ENC[AES256_GCM,data:7Bu4BwMXkxXs1suXeJ+myUDnEiLbL56x3NCfyxxsnTFLZbiy94pbc88zno8=,iv:5WgjKLtnksUkOKDe4xTu+Hgs5d0Ab9MhYk4RLYCtzNs=,tag:Hu/EDyuOHJeYQiRrPXBi2Q==,type:str]
    r2-access-key-id: ENC[AES256_GCM,data:xpn007n9nWY42c1vZisxOCnR9wLxC5J9TanlbNX6xbo=,iv:ULGRnj3GMwYJq7FD2tjS96DBJtJdzaoNKE17KJOhqRo=,tag:6xDHRnraT7IFTUNWEXfWRA==,type:str]
    r2-secret-access-key: ENC[AES256_GCM,data:UtiZB6t/MLPfbHDyrAVi7VmiHvtwJ1v+G6DClKa2IgXjM09hiRcSbRgBpjCDfQwb1t3cA38N/mKbKYaiGpp1RQ==,iv:E91iZixH46z/LTjiR6ASds8dR2lfz5iedzjnbmufCpo=,tag:O45omcAa5SMYSoGdC53kMg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NkVIQkpvWmd4c0xaa2dk
            TDNEVVhEdUR6T09SNGtHN2JMenMzalFab3c0CjBXSm1VSkFtRy91aWsyRFcrdGJW
            VG52YVBhK0Z6TExnOWJrclpkZ0Faek0KLS0tIDhnZVMzQSt6Q00wcjJ6MCs4aG1D
            YW5CQnlMNk1jUVR3ZUpYelFUM1pzREUKAUglpBBYM/JgXYJvJz/JmAqXyFMWLXFw
            NnsJeXjE7wjaeVCg29/qH7DXAF2J0hnr4L4iOoDCqEZYqOPoO0gyBQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T10:46:46Z"
    mac: ENC[AES256_GCM,data:ETk2q/8Y8IFsFEBPcVF/wFHJqocvUQKrvtcytdjbq/GE1EJvO5w65CTbqeDMbzjpHFZbjgumic0rMBpzGsXnMXBY85zI4jYfildRGP32lnw4OEWl/UmhDP6Z8cEYygY5nM1I+g5NTpXQFEkKoyxCrO2d2KArpz3Mxj2P3tCRYws=,iv:SDVf/pt8abysODQ7oZ9RJh0Ga5cllWW8MoiN4/lyEz4=,tag:xGJQfXcSxTefPammcdypXA==,type:str]
    version: 3.13.0
