apiVersion: v1
kind: Secret
metadata:
    name: qdrant-secret
    namespace: qdrant
stringData:
    api-key: ENC[AES256_GCM,data:7Bu4BwMXkxXs1suXeJ+myUDnEiLbL56x3NCfyxxsnTFLZbiy94pbc88zno8=,iv:5WgjKLtnksUkOKDe4xTu+Hgs5d0Ab9MhYk4RLYCtzNs=,tag:Hu/EDyuOHJeYQiRrPXBi2Q==,type:str]
    r2-access-key-id: ENC[AES256_GCM,data:APJ6aLbVJidJ7vAxr/ixYqLSNm9G4vw1SwlFuaTPnTU=,iv:2WRTSu/x+oxuGL9l1YjCzBYqHadZVRVjOZr166VK2UY=,tag:tg9cr6mQ4BnysYj40Vetaw==,type:str]
    r2-secret-access-key: ENC[AES256_GCM,data:txyylfHfs41OFGY6eYdXcxRVWEX5TL5eV0htiWKfryOgI7L9gP72yIazGbUmW/1RFZ0h6NyG0zESv2XrwxKB8w==,iv:qisPhElT7tqlOce1tzo2c3Tfm71j5hg8PwSuEN5dgnk=,tag:J9xpXaNrUeoD9xlPz+LPxA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NkVIQkpvWmd4c0xaa2dk
            TDNEVVhEdUR6T09SNGtHN2JMenMzalFab3c0CjBXSm1VSkFtRy91aWsyRFcrdGJW
            VG52YVBhK0Z6TExnOWJrclpkZ0Faek0KLS0tIDhnZVMzQSt6Q00wcjJ6MCs4aG1D
            YW5CQnlMNk1jUVR3ZUpYelFUM1pzREUKAUglpBBYM/JgXYJvJz/JmAqXyFMWLXFw
            NnsJeXjE7wjaeVCg29/qH7DXAF2J0hnr4L4iOoDCqEZYqOPoO0gyBQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T03:59:54Z"
    mac: ENC[AES256_GCM,data:frzDvirZdNPurhPYwPWJjImnGiOwov9q/Vyfox3ZsdmijS2uzMM2T7/rSSJif1/VWSOHSb6UHFYi7TGrYksn8LTSDjSUmNkOKvHcyozSjE1cIF0WUSjtriQpImBg7NMi/iaALwe3U3pOzjL1hsZYGVsAqyKw/j6OkJddx7yV984=,iv:GKVeNCKfB4Hfcw0HFnf57ESAWzi4luVWYWGuTMtgP90=,tag:UKTk0CIFFpM6K81wky1iZw==,type:str]
    version: 3.13.0
