apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../system/victoria-metrics
  - victoria-metrics-eso.yaml
  - alertmanager-config.yaml

patches:
  - path: victoria-metrics-patch.yaml
