apiVersion: v1
kind: Secret
metadata:
    name: victoria-metrics-auth
    namespace: monitoring
type: Opaque
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:p3BGkmKtIGoveLEsmFRBDtmLyMQOAbDZRxXp8nNpdsgJGMIozEpomBWSoAdYEIEODSE9yo4R4cnmSVYLJltKZA==,iv:npV8EdpAfc6JYQpGutKE3Qw+gejbv7n5bXZ338hgtlw=,tag:JTk2C3w50/1dYQPEfspE8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1aDZaQkhMUHNQcHk1YWsv
            QWFISjc4bHFhVVMzejJCRno5aFErOVVwa1dzCkRIdVVZdGVlN2lKV2hXTytFTzNC
            RWM5NGFRZUhGZllnY0picXEvdU1jcFUKLS0tIFZnVjhjWlB3RlNIV3JQWE95ZmxX
            SE5wQzBPeFZIVXIyMVhWYnVsd1lIN1UKyR6mjhFiZ/G7R6TH2u4+m9HCvlZljhqr
            iIXQ8XSFLH1QdAb23d566a+0K9g3WkkrbkjjK+VqknYeU0fhLzgo4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-23T04:40:17Z"
    mac: ENC[AES256_GCM,data:Y5BAXlGsiiY7pRnMNYpHmCreW020t5uZUWw1NxPn6QVc7G0gu+w6P7zqUY8ypYA+loW2BCNIMFgn2/XTMATR7RLz9DTd5gPfR44ojKIhCnMWwIOiH01jOxdmvaXCliuHOHMhrSR1dyYmYOt5kl+0Vs+3FSquvd98MN243sO49QA=,iv:ihddXtGAOLD4wiJ6dfXrRG8e9lUWgoHzfNKH/VhFFik=,tag:I0PAGXeKRjg4rdWRhJt8Xg==,type:str]
    version: 3.13.3
