apiVersion: v1
kind: Secret
metadata:
    name: vmalertmanager-discord
    namespace: monitoring
type: Opaque
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:1pI4wGU1/MvrtsuvU7N0rLsl7ErAdqLqRx8dH51r2uoSkCWkGCwRDPXp8aQmHO8gY65cdJD2CXGRj8SeLkrG91HGn1PE4F+bO34UoxFC/jQV1pyP1aekPnbxpe7GCTRUqrzo7FHg1fCSLxxteX9Gg2zhzzP50I2/l5zhyiyMHQpByvVHaYJs57EJE3cuMVgDR/P7IBf9fqnMfK0EtCf5UQBPV5st73D4gSRCb291ee4xYui3puMQqNYbKqqS+vkY1/M4NXcO3OE7MdHMXDPgON7NfqOyA/59ONvUPcNTGLS1Tq7PGWza852QFqPo2RXAkFCQeSVTFWnQXMkTHn5XLl/WAcvcnieQqHl8YA2C4NRqwIzh2t/RI36XQXBYTWbt/Sj+zluP7dN0lo9mt1f/qTdXrt4uDo6cAn7wlnIgD+ix08SYPBe7UoP5T9RPQEcCxsTNxV4gD8USstNZCCSfPvX9EgaFZhPHN1l2WO7U4DMQzAsUB2imJElkaKvTI1g9eV6XvW12dSGnvWUCGwPvatEpKFqUp759ZS8AosumJwsly+vOhQ==,iv:W3mS8AUdwv9QANjlPLvP7QT5DPyOJrsNdgEnSsmV68o=,tag:LXPVelYeAi73D8+9ZRgfjQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VkwwMTRyMjhsa2FtS0p1
            cXhrNndreHk5bC9DcFFUeFkvVDllUGdoU1dJCm9oRDBCK2s2UWl6SUY1ZHJjZW9w
            N3M0bW5aM0x5cVRYMTNTTnFPWmdtKzAKLS0tIGk0Z29ENmtNWDZzQXAwVTlvdWJl
            T0RvK251Y1ZYZ21FU1E2bk5pdUxDdkEK3OE8PxzC7pTGIM5IPzW2OAqobox4zYG5
            cBh21VI2nctz2AeP8Z8NOeFUtRXeR8VlfEJg7IEmEBfQo27CoaIm8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T12:35:32Z"
    mac: ENC[AES256_GCM,data:rH6gvTyFZ2QALmdrNqaHIOA9whEIkaGoMSVslMGrD/W5cmOPsH1i0iPNG1VANSwlqfeKOeI7F2DbvZcND++k1VreXLRvUWqm4PmlBLOecWwMXO6Z5ck/KgSKesNcMeRc+9oojEjgHxuJTi3DYGDpKXcXlaJgX2PFW9vWtKKGgAE=,iv:SGJa116D4/W4Pf2I33te5Bb18ceT6Ybv1BJqzSNhINo=,tag:lRpM2pwdsGQGO+z8B9Xwwg==,type:str]
    version: 3.13.3
