apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-operator
  namespace: ot-operators
spec:
  interval: 30m
  chart:
    spec:
      chart: redis-operator
      version: "0.22.2"
      sourceRef:
        kind: HelmRepository
        name: ot-helm
        namespace: ot-operators
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
