apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: image-cleaner
  namespace: image-cleaner
  labels:
    app: image-cleaner
spec:
  selector:
    matchLabels:
      app: image-cleaner
  template:
    metadata:
      labels:
        app: image-cleaner
    spec:
      tolerations:
      - operator: Exists
      containers:
      - name: cleaner
        image: alpine:3.19
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -e
          apk add --no-cache curl tar

          CRICTL_VERSION="v1.28.0"
          echo "Installing crictl $CRICTL_VERSION..."
          curl -L "https://github.com/kubernetes-sigs/cri-tools/releases/download/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-amd64.tar.gz" | tar -zx -C /usr/local/bin

          if [ -S "/host/run/k3s/containerd/containerd.sock" ]; then
            ENDPOINT="unix:///host/run/k3s/containerd/containerd.sock"
          elif [ -S "/host/run/containerd/containerd.sock" ]; then
            ENDPOINT="unix:///host/run/containerd/containerd.sock"
          else
            echo "Error: Container runtime socket not found in /host/run/k3s/containerd/ or /host/run/containerd/"
            exit 1
          fi

          echo "Using runtime endpoint: $ENDPOINT"

          while true; do
            echo "[$(date)] Running image prune..."
            # Allow failure of prune command without crashing the pod
            crictl -r "$ENDPOINT" -i "$ENDPOINT" rmi --prune || echo "Prune command failed, ignoring."
            echo "[$(date)] Cleanup complete. Sleeping for 24h..."
            sleep 86400
          done
        volumeMounts:
        - name: run
          mountPath: /host/run
        securityContext:
          privileged: true
      volumes:
      - name: run
        hostPath:
          path: /run
