apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: shared-postgres
  namespace: postgres
spec:
  instances: 3

  # Add recommended PostgreSQL parameters for tuning
  postgresql:
    parameters:
      shared_buffers: "256MB"

  # Add recommended resource requests and limits for pod stability
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

  storage:
    size: 10Gi
    storageClass: longhorn
