apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisReplication
metadata:
  name: redis-ha
  namespace: redis
spec:
  clusterSize: 2 # 1 master + 1 replica
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
  sentinel:
    size: 3
    image: quay.io/opstree/redis-sentinel:v7.0.15
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 20m
        memory: 16Mi
  redisExporter:
    enabled: true
    image: quay.io/opstree/redis-exporter:v1.44.0

  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.15
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 20m
        memory: 32Mi
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi
