apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisSentinel
metadata:
  name: redis-ha
  namespace: redis
spec:
  clusterSize: 3 # 1 master + 2 replicas

  # Redis Configuration
  redisExporter:
    enabled: true
    image: quay.io/opstree/redis-exporter:v1.44.0

  kubernetesConfig:
    image: redis:7.2-alpine
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

  # Persistent storage
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 2Gi

  # Sentinel Configuration
  redisSentinelConfig:
    redisReplicationName: redis-ha # Name of the Redis replication to monitor
    masterGroupName: mymaster

---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisReplication
metadata:
  name: redis-ha
  namespace: redis
spec:
  clusterSize: 3 # 1 master + 2 replicas

  redisExporter:
    enabled: true
    image: quay.io/opstree/redis-exporter:v1.44.0

  kubernetesConfig:
    image: redis:7.2-alpine
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

  # Persistent storage
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 2Gi
