{{- range .Values.nodes }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xray-{{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "xray.labels" $ | nindent 4 }}
    app.kubernetes.io/component: xray-{{ .name }}
    node: {{ .name }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "xray.name" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      node: {{ .name }}
  template:
    metadata:
      labels:
        {{- include "xray.labels" $ | nindent 8 }}
        app.kubernetes.io/component: xray-{{ .name }}
        node: {{ .name }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: {{ .name }}
      tolerations:
        {{- toYaml $.Values.tolerations | nindent 8 }}
      containers:
        - name: xray
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          command: ["xray"]
          args: ["run", "-config", "/etc/xray/config.json"]
          ports:
            - name: reality
              containerPort: 8443
            - name: http-proxy
              containerPort: 10809
            - name: socks-proxy
              containerPort: 10808
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/xray
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: {{ $.Values.secretName }}
{{- end }}
