apiVersion: v1
kind: Secret
metadata:
    name: open-webui-secret
    namespace: open-webui
type: Opaque
stringData:
    #ENC[AES256_GCM,data:ZhDft7x/cT8LfSL2CinA,iv:0wcYdUWw83FOxId+uHmXaIScO3/NWnka2Pv/K3s1Los=,tag:V6C1WW1RATPQYO+yS6C4Jg==,type:comment]
    #ENC[AES256_GCM,data:aueB0kU1pyCfbrbCN3v5mkrEumOOBQdq5KT2/TwB5o3G1qDPNT/Dvp4Fw9sG8DBc,iv:pE5X5EQZK0sqNXm6Ie1X/z0lsahYfqRs+O1By3v9Hc4=,tag:nvA+OZw+5SMUEBshUd503A==,type:comment]
    qdrant-api-key: ENC[AES256_GCM,data:xJXpW9LN6fPx6lS0nglgyWFFA53m0lBxVCNGynGcFhLfVh9sTZ2vsKPcCCc=,iv:n7c3wc3M1d6sVZldXOAzu/TyI6I7HeivYFImixbZw8k=,tag:TK13IIAS7N9NgBkMcv3iFg==,type:str]
    s3-access-key-id: ENC[AES256_GCM,data:TvOF45AzhVsDfJvolaUZ3dnpCGHrmn+VUHhrFos1UZU=,iv:4S0Too5rbCp04cGeN1Rdkxng0rlWh4rP4OWgfADNpDQ=,tag:94/bMQOakRlaeIK/SNZa7w==,type:str]
    s3-secret-access-key: ENC[AES256_GCM,data:I9iRZF5kNDXG3HMzmtfTSglb7tKfSuUwgfgDP3xjCFMs2zn4TAkMJ8lEV7HCpnAMS7/yan/IsNt/05iqMLRa+w==,iv:eZdV3ieVXmAyeQkgM0HTTKFj0MNmjIYTKKsDEmaim0Q=,tag:oY4MCcCArwlPYlSnpBwMMw==,type:str]
    s3-endpoint-url: ENC[AES256_GCM,data:t9t61RAJUw4QW4ucQIvgOi8lkHU08dsiUOq8xJ3WH0ZwazMq6Emgrxwy/fSk7IJQwlduIyonuUH0XGEEUt4ci/8=,iv:QoGDEdqZ7aF5+cqv7tKT7oeeh+aKiKVlNH/XPU8stTM=,tag:zjgi0pEDI0Od3w+SkYLBkQ==,type:str]
sops:
    age:
        - recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dStlczBpWllRTGhKSWlV
            VUtlWnE4UWQ0TmRsS3l6TEFxZWhtT2RMeFYwCkoxblVyeU9UcUxVL2lCVEpRNUZX
            OWRpOU9GTkdWZXF1WmQyRG5YOHkyYWMKLS0tIFBkanRHZ3hwSm5qWnJVd1lWVmlU
            SkppM05QWU5Bc1g1UlNiZWFLK0dvdncKW/i3avRQVv3gKf0+a31nV7JALcAoRvmt
            jW4DUlACONSCjZg4ERjv37m9RdQYm+WFMw3fUmfOoYQP1KWqyUv3yQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T18:13:18Z"
    mac: ENC[AES256_GCM,data:mxRoqbLsOwU9ZGpD+th9Cy0bn8NABXwqpp50Ah8LV29sqoV0ESc1FWCUOfQD1Mls+LN2/+xG1eCBI7oJ0574sWXyQA47Ef1/BGF7bYCiZoRePV7NhO8DK0bGyR8Sl4qqsma2BAr83jJ0E+VXHYvr4Bj4q/6F/SS7cp9kIPo/yQk=,iv:ZqKhFLyAB/e7LPY7pJx2xjDgqnOeyWUxa7g1aF5qGEs=,tag:RL6ZV+sSzmpFMcO5BlxLlA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
