apiVersion: v1
kind: Secret
metadata:
    name: open-webui-secret
    namespace: open-webui
type: Opaque
stringData:
    qdrant-api-key: ENC[AES256_GCM,data:FoImlgPgK+8wih3zZXpkBzqR/+rfmGoXywk52JS+3ibW7G26THTvsETNmBQ=,iv:Ozn0cQkaPtyTRmGoBMZicWtBPu8kqD4kSG3z5LFWXBY=,tag:kATdxB6WUfGAtGckvjejNg==,type:str]
    s3-access-key-id: ENC[AES256_GCM,data:WIjl2an5YXz3Q7asG6zvyKEpIcYspXNMhFvmP+Tgbqg=,iv:xrm6Jw9GnUqWMxTwqejRF30skYRB3csrXgHCwcMR2gA=,tag:cHt38pu/rtzL6T9bWiRzQQ==,type:str]
    s3-secret-access-key: ENC[AES256_GCM,data:Uo6XD755zJ3+HRkI67igy7zOyt+TyBo+N8QYUWEzEQCyFQ4t/6KERsy0XgTqNcow2RelTIprEbkXdVuC48p9Ew==,iv:/6uuzHhVv8qZU4MKAKt66hQG4VP5Cxq/AL3EzZOozpM=,tag:ImyxmaZPMeR7sa9fHncjlg==,type:str]
    s3-endpoint-url: ENC[AES256_GCM,data:EohTbtAQJ5VOdmWtMKuUBSVrq+wzHB1abtX9v3HxmCDhQHXNov34LOXCRZu87ocGtlRCNS1FZgmBhbSu+hFKiG0=,iv:SLY8RqVrSy7jvneTFM5rzi6ksraWGSy5DwM6NTdvpqo=,tag:y8jKL5p3CxlLOx2PiHA3wg==,type:str]
    oauth-client-secret: ENC[AES256_GCM,data:vtU20g/JiqigzPmY1TI9s4SeDBcBllj+/bT8KAgJUyhuK444OJBwRaqu5APwIhFr,iv:cWH3ha9A4UCGBIK0T/mLUhukTX+BPKB6VLnwbzMDORc=,tag:ET1DOK1ckDqCorndWwbOYg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBOGZOd3hlUjh6R2plZk9W
            eEwrRGMxN3dDL1A4UlVRRFhNTFpFZ0J4RVRjCjNZYXY0ZmVMdExPZzBrNXFzdU5i
            UzU4bkRhaERlQnlnR2w3M0hpcU50S3cKLS0tIGdXYW85eVpQbVFzVktwNmxKM1h3
            NEl3eFIxdmhLUmtoekdXdXJBdE1JbkEKBXA1RS1+2ZP0vddLFcw8OnQ9rBIqPt7O
            K2gVJia7qDqpJjV/rzQRjpORGc7MDrIoV/wJhzjXG7W8Yqz179xjdg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T04:16:10Z"
    mac: ENC[AES256_GCM,data:iVFKCNPcHB80yPrZyiZEUK1j90LL2pU7lN2fTyoniyoHXsEpLg3+V0q/ekXiRRk2ZPFVhTVs0H1y/3NIh3Ct/91sy52u3ciAgeMc6Tfl88d4sU9/cBZ40uD8jRoOaA5zgBydOb/WWi4MhX0wPFOCoUXwyuDktc8jtf4YxBU8MW8=,iv:EYV8ZKNqi8oiLFjPn0NIlYcCSdUWbkKLyWbXetITlmE=,tag:p43MHKYhfxRMP6tW80K+3w==,type:str]
    version: 3.13.3
