apiVersion: v1
kind: Secret
metadata:
    name: open-webui-secret
    namespace: open-webui
type: Opaque
stringData:
    #ENC[AES256_GCM,data:ZhDft7x/cT8LfSL2CinA,iv:0wcYdUWw83FOxId+uHmXaIScO3/NWnka2Pv/K3s1Los=,tag:V6C1WW1RATPQYO+yS6C4Jg==,type:comment]
    #ENC[AES256_GCM,data:aueB0kU1pyCfbrbCN3v5mkrEumOOBQdq5KT2/TwB5o3G1qDPNT/Dvp4Fw9sG8DBc,iv:pE5X5EQZK0sqNXm6Ie1X/z0lsahYfqRs+O1By3v9Hc4=,tag:nvA+OZw+5SMUEBshUd503A==,type:comment]
    qdrant-api-key: ENC[AES256_GCM,data:xJXpW9LN6fPx6lS0nglgyWFFA53m0lBxVCNGynGcFhLfVh9sTZ2vsKPcCCc=,iv:n7c3wc3M1d6sVZldXOAzu/TyI6I7HeivYFImixbZw8k=,tag:TK13IIAS7N9NgBkMcv3iFg==,type:str]
    s3-access-key-id: ENC[AES256_GCM,data:v0B7r4lrckgmPZeBTOi4Pqxi2i4kKCt9ZPWVw6WLMLk=,iv:O4hc8m0kRWeMY5Bl5N695ohNSYw3zmnly3Tj99feFcQ=,tag:OkJ4CR4An/EbL0ZtE0MEpw==,type:str]
    s3-secret-access-key: ENC[AES256_GCM,data:FiG4Gi4Oa8ghvN1Xtlv0L2FVS+D0b2pPNcy7/QnUfD8V43Bg5yLIlSRVx7AB2AVVD0mbME5EyGEvaPof0xm6ug==,iv:XOylzUfZp6/3JPH757z/+UsUS4kSzsYEiZ5CPiZIghc=,tag:tY8LPzQGYELG3b4tfriURg==,type:str]
    s3-endpoint-url: ENC[AES256_GCM,data:t9t61RAJUw4QW4ucQIvgOi8lkHU08dsiUOq8xJ3WH0ZwazMq6Emgrxwy/fSk7IJQwlduIyonuUH0XGEEUt4ci/8=,iv:QoGDEdqZ7aF5+cqv7tKT7oeeh+aKiKVlNH/XPU8stTM=,tag:zjgi0pEDI0Od3w+SkYLBkQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dStlczBpWllRTGhKSWlV
            VUtlWnE4UWQ0TmRsS3l6TEFxZWhtT2RMeFYwCkoxblVyeU9UcUxVL2lCVEpRNUZX
            OWRpOU9GTkdWZXF1WmQyRG5YOHkyYWMKLS0tIFBkanRHZ3hwSm5qWnJVd1lWVmlU
            SkppM05QWU5Bc1g1UlNiZWFLK0dvdncKW/i3avRQVv3gKf0+a31nV7JALcAoRvmt
            jW4DUlACONSCjZg4ERjv37m9RdQYm+WFMw3fUmfOoYQP1KWqyUv3yQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T10:46:35Z"
    mac: ENC[AES256_GCM,data:iVIACDFFjXnp5UpT5gNIs9Xc/bDL8C9pmmV7VGSO+DfrcJm8auvxTkL2M2N86/uaZjzhlh4PPTCCOVkb6fobrXFkGo8DO0Hlhha8OzmruLmfPy0DlLIIzIP3N02NLPkt2QrrfyqpOCEu3CATelFaqc72IKJ1yGE/C33AJi/c7rE=,iv:lx2eobbQUbsRko53EQtxgJmNTSZBXCdXIB3uFKnCvOI=,tag:/jAPxx0nI8YvE2mJF4+FHQ==,type:str]
    version: 3.12.1
