apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: open-webui
spec:
  interval: 1h
  values:
    websocket:
      enabled: true
      # Using external Redis (defined by 'url'), so internal redis is disabled but manager is set to redis
      manager: redis
      url: redis://redis-master.redis.svc.cluster.local:6379/0
      redis:
        enabled: false
    pipelines:
      enabled: false
    tika:
      enabled: false
    persistence:
      enabled: true
      storageClass: juicefs-sc
      accessModes:
        - ReadWriteMany
      size: 2Gi

    service:
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: "open-webui"

    ingress:
      enabled: true
      class: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      host: chat.simplelumine.com
      tls: true
      existingSecret: open-webui-tls

    commonEnvVars:
      - name: OFFLINE_MODE
        value: "true"
      - name: ENABLE_OPENAI_API
        value: "true"
      - name: ENABLE_OLLAMA_API
        value: "false"
      - name: ENABLE_ADMIN_EXPORT
        value: "false"
      - name: ENABLE_ADMIN_CHAT_ACCESS
        value: "false"
      - name: BYPASS_ADMIN_ACCESS_CONTROL
        value: "false"
      - name: CHAT_STREAM_RESPONSE_CHUNK_MAX_BUFFER_SIZE
        value: "10485760"
      - name: REPLACE_IMAGE_URLS_IN_CHAT_RESPONSE
        value: "true"

    extraEnvVars:
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: open-webui-db-secret
            key: DATABASE_URL
      # Qdrant Configuration
      - name: VECTOR_DB
        value: "qdrant"
      - name: QDRANT_URI
        value: "http://qdrant.qdrant.svc.cluster.local:6333"
      - name: QDRANT_API_KEY
        valueFrom:
          secretKeyRef:
            name: open-webui-secret
            key: qdrant-api-key
