apiVersion: v1
kind: Secret
metadata:
    name: garage-secret
    namespace: garage
stringData:
    GARAGE_RPC_SECRET: ENC[AES256_GCM,data:yDSMIQn93/TH1iEJORdTmN4Jy5okErQhsXfcGXrTQzhOfD50iVJG5nDRDyBo++Sww6es/pw+7w2Vv0QaRrdk3w==,iv:Cp3zlmyDpMQiQCSaIFCMocczgQTRuw8jNyQ80cscaVA=,tag:g6U2qzG6wJhnZSCCSg+6SQ==,type:str]
sops:
    age:
        - recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdGpBUFFmb3F1MGhZSmNN
            eGhTeXc2dHUvc09WdURYYXlKc3QvTXhKb240CkV5RWh2NzN4aHcrb1ZDWDFHNWwv
            L0R3U2Vkaml1U1c3dHpjdkZjOWtOcm8KLS0tIGRwWk0xU29BaE03K2JZQnppWFVm
            bUNSYlVRZzZLOU1vOWREN0tWM1ErcWMKFBmGxvJroRUUJI+EKVih32D0e8lQdXmn
            adidbma3bFyucdPK6TsMSu+OQ/S3ADgGLZmH+cVI+BbESlwTa+O2gQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-18T15:09:37Z"
    mac: ENC[AES256_GCM,data:UKjwBvLae3MGWvJzFUIktGNyjlYzrn1aHhdwNHOPVGcf1tuq4xysrQYG3qdlzI/gD0v5M6F2QNv2n8b5A2x+5aFco84CNME9YW6wa4SrQEitixyMnjZbzPFbiCixC2099jKYFP5uw1Bs42ZDUyMHzHbaE24lpF9w7Hr5YnaSbyM=,iv:/a8AiMEVuCY7dSX5n+F/d0sgF0+H6WJ4sj5s208sOvw=,tag:1x2pAQy00PQQGbFtAAAxJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
