apiVersion: v1
kind: Secret
metadata:
    name: open-webui-db-user
    namespace: postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:kooL3WGl4XzgSg==,iv:QOlqMbTmJ740DmjHnfUm9YacK6wUmErOg/n/6L3zfYo=,tag:iphgKwIsT2ANE7BnMQC4ug==,type:str]
    #ENC[AES256_GCM,data:Apnnln10Udama3EeOx+PLm6V5AIE/rYKgRESx7kE8mmcQA==,iv:lacIDKks7mHYwRfQ3262pofsst40C9e+9mEesxVUz4A=,tag:3vwjnNEXZN11ur5cBPJUrA==,type:comment]
    password: ENC[AES256_GCM,data:VEfc+aauKam/Nbsq2+Q+yOEJQQ/aVLE=,iv:nuxvr2MgeG6wTAdRlsoQWvsQ46LCPxVkyIms1K19pW8=,tag:4xDnZYsdPepgfoi0UIrK1g==,type:str]
sops:
    age:
        - recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmT2tlNWdOMkFFTG9OT2Z1
            RUt3dkF5V2RCdjhZOTNiTksxOUZLK0hvZURJCmMyQXAyYkZUMlpsTmhPSlZkMmZC
            UDR5ZnJ2MXBka1IwQ0VmWGJJUEExc2sKLS0tIDJ6N3Rkc0JqVnEvRFNOci9DVkt6
            QXZ1aUpPUmZQMDE2Sld5NXdoRlVQQzgKk/tk7tTFqEHjrh8cjwa3178wlPjV1x2s
            wIes9DMk3v+DTXfMdHEahnqGlRTcli8WuFFD8xj8gHsocKeVHKY95w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T16:15:38Z"
    mac: ENC[AES256_GCM,data:xDludKHmOxEA1VV+OqSnLuNn8W5qwBkt+psotdg1JcdpXAeCb0GbVQKAIcK8P/r/VajJU+Ac5qH8pI7Kk/tkWSGvshKxa2TSVbbZ7JTkQ2UPCwsqwsJUoC31eZ4mbB+Odh+ABsKOXf6BcfgK94KDDZuvPoWCL+eybM16/kDPa2c=,iv:DdQNQUvF0beoNfjB8oYgSDn+dIIvhrUuOBnx94PC8eo=,tag:n1n9ji2DEx6zMKgntvOqWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
