apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  valuesFrom:
    - kind: Secret
      name: cilium-secret
      valuesKey: k8sServiceHost
      targetPath: k8sServiceHost
    - kind: Secret
      name: cilium-secret
      valuesKey: k8sServicePort
      targetPath: k8sServicePort
  values:
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
