apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  values:
    k8sServiceHost: "96.44.157.40"
    k8sServicePort: "6443"
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
