apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: open-webui-db
  namespace: open-webui
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: open-webui
      owner: open-webui
