apiVersion: apps/v1
kind: Deployment
metadata:
  name: sillytavern
  namespace: sillytavern
spec:
  template:
    spec:
      priorityClassName: high
      containers:
        - name: sillytavern-container
          resources:
            requests:
              memory: "1.5Gi"
            limits:
              memory: "4Gi"
