apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo-runner
  namespace: forgejo-runner
spec:
  template:
    spec:
      containers:
        - name: runner
          env:
            - name: FORGEJO_INSTANCE_URL
              value: "https://git.simplelumine.dev/"
            - name: FORGEJO_RUNNER_UUID
              valueFrom:
                secretKeyRef:
                  name: forgejo-runner-secret
                  key: uuid
          resources:
            requests:
              cpu: 25m
              memory: 16Mi
            limits:
              cpu: 2000m
              memory: 2Gi
        - name: dind
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 2000m
              memory: 4Gi
