apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: reloader
      version: 2.2.7
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: flux-system
  targetNamespace: reloader
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    reloader:
      watchGlobally: true
