---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: ">=1.18.0 <1.19.0"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    # Infrastructure Settings (Align with Ansible)
    k8sServiceHost: localhost # Overridden by Overlay
    k8sServicePort: 6443
    kubeProxyReplacement: true
    identityAllocationMode: crd
    l2announcements:
      enabled: true
    encryption:
      enabled: true
      type: wireguard
    hubble:
      relay:
        enabled: false
      ui:
        enabled: false
