apiVersion: v1
kind: Secret
metadata:
    name: zitadel-secrets
    namespace: zitadel
type: Opaque
stringData:
    masterkey: ENC[AES256_GCM,data:enw+PTNiiDZ7XAAfKf+J0r3PWVi/mFGpzw5XRBrE99M=,iv:QGiWhOV9xBnQ9Q/OUwtkID3lmzdMcfY+s6ADrkrdgwc=,tag:nYZL1ZNONvKYHqU6QwOYhQ==,type:str]
    adminPassword: ENC[AES256_GCM,data:JpBebK085HGnR1R1o5sjh09fmhN2,iv:OgDAyJo+Uy+lmGHRj6HFB152mbGBafrtSu53KxvgtmM=,tag:mk1LEczMCxfrNiHKBiDGUQ==,type:str]
    smtpPassword: ENC[AES256_GCM,data:kGf1nJEGeETmNX6d8N1wK73YgGewwyC10Su01MTVKR0ParRJ,iv:O4HDUq6Gc0LBzwt2wYzVjkH3M6kuKLr9sg8y1sEI0nQ=,tag:cOFrWhoPfZ2yujj/2y+8QA==,type:str]
    adminUsername: ENC[AES256_GCM,data:wLb9VAKIv4os4L+f,iv:bGx7B5Qb8/M+ORt2zGU7K04aRb9/c9vh8M/m0egj4AA=,tag:VdhOlhya2lGubWE9dqfP4Q==,type:str]
    adminEmail: ENC[AES256_GCM,data:CeM8sMuhB+WS4woUdPZ5PJUiMMELWw==,iv:UGpMChnOm0/UQaMX8FNJPAdst5qIe4hM4ntsYENiaj0=,tag:v7hfXywb29w3bHaRCRcrUg==,type:str]
    adminFirstName: ENC[AES256_GCM,data:FOjpcmxu,iv:9Dm1v88V3GzcI0C4FkxrI1Tjwj/XAvgyU1vQlH7JX0s=,tag:z67NwUt06MxYCBwNjBQedQ==,type:str]
    adminLastName: ENC[AES256_GCM,data:RO+q6LtD,iv:y7ttr0sVz2KpKPdglZT/5aIMu2bNzhLOHoldym0uzDg=,tag:Py9mcMWyCAtGT3XpdeISAQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQzRkTWk5UTU2OWRBWTAw
            N1FHQjIyQnJNOTNHL2JlTEVnendsL3JKbmljCmplVlQ5bU13ditUbU1VTE5qSDNJ
            ZWFWTG9Dbmc0MkFZd0IvZ2lESVR3K3MKLS0tIC9JdVdqQmQ5aDQ4TGxiR1BOQkRU
            N1dsdE9Nb29FNllka0tTbHhOcEJzcEEKGg2l8ffH6QFB/zx5jPn29a7yJ7WhOs1E
            Td+wJbXYyLn2H2O+Tlr6YGOoJCTajaKS9FzsDOsKHU7gJknqsEB/7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T01:18:34Z"
    mac: ENC[AES256_GCM,data:7O4NotO6TiaX4kSU+h44RH32QThsthGmcBnKtcdRypcuIMJ4/xhcYJGEot/h3D4VPPQ0clLy8hiVIHI4n+Az/mVjeBWadfJoLYEDbrmGLs7IUpHPPOmOGLEfxzC1F5FjRsoIbYEi3sRVjYS0NCZEmE+MvVKHtZyv5942TTUTYHc=,iv:HaDEw1+MJvNAKomQk9M2NCWyRPJqesfn+g574P65jxw=,tag:SxfFwoSV4+KPoDMZWKZMfw==,type:str]
    version: 3.13.3
