apiVersion: v1
kind: Secret
metadata:
    name: zitadel-secrets
    namespace: zitadel
type: Opaque
stringData:
    masterkey: ENC[AES256_GCM,data:GmxwniPLhNHS0Wdb78pgAoUE26x/jTFRRMQVOUEJCtw=,iv:C5Sjp5XTvUUYzR9xMidv/8bn9pBZboi9tP4vZwNd99Y=,tag:rfagKrMxBNQ4UONpB+v7qA==,type:str]
    adminPassword: ENC[AES256_GCM,data:46JnTlLFfw06SzeIS5UlOcEvAtE=,iv:LgY0SfHOz6TONM3TFQ2zbZMusXSVRIeAi/j/Yb4DpZc=,tag:3Ta3DV2byZNQbtAOECkU+A==,type:str]
    smtpPassword: ENC[AES256_GCM,data:p5/ttZhpKX9R+mdMHtCjVicIWJrimrQ1qHpYhDrJ5/KFktDL,iv:kGgm7BZ4CTK+PyllZQQN6gsze/L9VXS5a4puAqIcvbY=,tag:PPrhKFf4I03lr39BmHduXg==,type:str]
    adminUsername: ENC[AES256_GCM,data:mZxAUOGqT1DSUijE,iv:RxcqjUpopbywMEKvtTg5THVrApbWpTqo3Dnx8Z1z7WA=,tag:r9NZPY0t1n+vjZvwrs/XRQ==,type:str]
    adminEmail: ENC[AES256_GCM,data:ms0L1ZDs1FFLOhP2oijqK5mgoC4wGw==,iv:tod1DdKz+3MQlFd1WJpWCgfv4EwsJMjXHSiKh+afWV4=,tag:OFnDEFSEbV1FniGGPRMuzA==,type:str]
    adminFirstName: ENC[AES256_GCM,data:TD6bFO5r,iv:h5oD/dt6GenzS2UWYDODVYovz5fIPCy62pjYihmcyts=,tag:q5FAi7yosviRpXGk3g/x7g==,type:str]
    adminLastName: ENC[AES256_GCM,data:Y2wCHvjB,iv:5DoeaSjOKbQIUSd+/NcPuhGlYr0q6Q+0ZvD4ClAv81M=,tag:lRUmIsSuIXmYQJZECt7TXA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoL2pJUVdKWmFqeXpoZ3pF
            MHNlRUhxKy8xL29LVXpqM2xPNzk3VFJjWjF3ClQwU1NjZlhZTmdaZHNJUkdqQzhN
            K0l3R29YWXRNdlVwdkM3dWJBWVNNVlEKLS0tIEx5NXgycDZaUndZbVFaaE5ldDdq
            d2tpZkluci9HRU5NWnZPWWdHT3YvbmsKPHWRQxGDWq6ayGX1kwUl4UZpY8QDVekV
            IVQXks+wbVpTrJA156Tls0TJYOiqBN+oPQ0XeznqT9j5tBX9u9NgPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T01:02:30Z"
    mac: ENC[AES256_GCM,data:pNoFCusM0PXJAMYn/LZ3GNMEHZJAxFflawOqL37dFgSctoobyjsXhPlc5eJ6G41mnAkvstLEtNjORxCGgSg3R/82Yr21YLYsYl3C4k+PyUbU8VGUEIlrfhRt2v0j6qLwCCxerIds5t5H0jLP6vY3Symjl1UWss3yJezK4vt7Jxg=,iv:szRhR7AhQnbxpavbHTITcO4AZZ280MBjQxVncjvCjmM=,tag:5pEsxr7knmPF9aFQMGeChw==,type:str]
    version: 3.13.3
