apiVersion: v1
kind: Secret
metadata:
    name: zitadel-secrets
    namespace: zitadel
type: Opaque
stringData:
    masterkey: ENC[AES256_GCM,data:K1aSYWZGu3LMkbfyB/vlmPXxDpfaK4JmNbJtI2cCk2Q=,iv:gNH1Z/taApr1V4c0mHM7aGNLhGM0KHz+4SdVVUjoqa8=,tag:2sQsISDQ40E4arvTI1q+Kg==,type:str]
    adminPassword: ENC[AES256_GCM,data:wJmDw6nBoij4AQI7B5L/Mm4H+2/S,iv:+lS2MC8rUCqBj5h8Nmccc+6w5yrPsjE4DaXMnn5HEnY=,tag:XhVWoPLVbzTkssu7Fw1nag==,type:str]
    smtpPassword: ENC[AES256_GCM,data:teWZ5CjdMKY/nU2Cs4w2stV5PCyqzKxWFqGBl5+dyYJ5gtCG,iv:uuNpnAG/UWABRmT4oRpBZh9tLH9O2L3Oi/1b3DHCIM4=,tag:5nD7021LpB0P4skuetzJUg==,type:str]
    adminUsername: ENC[AES256_GCM,data:/yx0ZEY=,iv:TYIr99w77ensq7hDfpPeaGUnMYgHWYwi9wnnxD4b86I=,tag:ylu78EQyiJKqmgHB6gwotw==,type:str]
    adminEmail: ENC[AES256_GCM,data:e7zerl06DsOQS1GCcy2Q5IIlMGvo3g==,iv:EDa7re2FTVjy7W0EZMHPsS48bAmR/BlF+Bv7u4WLhiE=,tag:jxOUQiN1k3scE1TXhMtrwg==,type:str]
    adminFirstName: ENC[AES256_GCM,data:hr7nx63C2Q==,iv:IyoFVU7rUqb8CiRCXkM3tbsLOWXQEAoUQd1NIF4v1M0=,tag:NXM7tag2sHT9KucJswzLdA==,type:str]
    adminLastName: ENC[AES256_GCM,data:QBZEmz4=,iv:a++xDpu/b0ymKW2LQ+wirXIWLQVGTnuB9nGjSle6/RI=,tag:J1Ek/yvuLYM57apqDEtBSA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMkpwT1NyS3dzYVBRenYv
            b2VWUEVudUtkOVlaSG54YXlDSzFnWWl4WkFNCnp1UWVudVZQb254MHgwV01mZHhM
            MFdZc2VkV1Q4UGFJUCt6MW9CbTBRckkKLS0tIEUxQ2JXMjBZeEV6ZWdJL2kwTVN4
            ekJIMjhBS1BkUFVLZTFiR1JGcmhzK00KdZVFGJqRQ+zme1P837Hepmd/Mm9diX+u
            krsrC75ioVPJCVWfm6u6AcGQWZcc2rgw59QcYWqN7jCG6Vdy05vfWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T02:26:52Z"
    mac: ENC[AES256_GCM,data:DiBo0TlMU4q4bUhp8bMgDOLhpwVP+LAnQ9je8Bx6JPX+8AgKZF7HhvmSl0bXn94kGBjudg6clTxr5rz79hk0vbFfCRyqMQAjv4+GQk5iayP913PTe0waKT8OuehAzqLWvTPwDE5fUGyqcdlSiBkGj4xbyB7+UGC4UWK/M82K1t8=,iv:2KzF0E9kci6iVxQajye4BbK2g/9t3X8uTV6TnXROn40=,tag:Gk872Oy08NnKyVvBj19GIg==,type:str]
    version: 3.13.3
