---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-ssh-key
  namespace: dev
data:
  authorized_keys: |
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILd86I5KYd05ofbDmnJuRl5eV5lSk9Lq44KRuf7cXqZ7
