apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: open-webui
spec:
  interval: 15m
  chart:
    spec:
      chart: open-webui
      version: "10.2.1"
      sourceRef:
        kind: HelmRepository
        name: open-webui
  values:
    ollama:
      enabled: false

    # Enable internal Pipelines for enhanced functionality (e.g. filters, pipes)
    pipelines:
      enabled: false

    # Enable internal Valkey/Redis if needed for caching, or disable if using external
    websocket:
      enabled: true
      manager: redis
      url: redis://open-webui-redis:6379/0
      redis:
        enabled: true

    tika:
      enabled: false

    persistence:
      enabled: true
      storageClass: local-path
      size: 10Gi
