apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sillytavern-data
  namespace: sillytavern
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 6Gi