apiVersion: apps/v1
kind: Deployment
metadata:
  name: lldap
  namespace: lldap
  labels:
    app.kubernetes.io/name: lldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: lldap
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lldap
    spec:
      containers:
        - name: lldap
          image: ghcr.io/lldap/lldap:stable
          imagePullPolicy: IfNotPresent
          ports:
            - name: ldap
              containerPort: 3890
              protocol: TCP
            - name: http
              containerPort: 17170
              protocol: TCP
          env:
            - name: LLDAP_LDAP_BASE_DN
              value: "dc=simplelumine,dc=dev"
            - name: LLDAP_LDAP_USER_EMAIL
              value: "admin@simplelumine.dev"
            - name: LLDAP_HTTP_URL
              value: "https://ldap.simplelumine.dev"
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
