---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuers
  namespace: flux-system
spec:
  interval: 10m
  path: ./environments/core/cert-manager/issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
  # This is the crucial part: wait for cert-manager to be ready first
  dependsOn:
    - name: cert-manager
  decryption:
    provider: sops
    secretRef:
      name: sops-age
