---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./environments/core/cloudnative-pg
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
    - name: longhorn
