apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: portainer-agent
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./environments/core/portainer-agent
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: tailscale-operator
