apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: forgejo
spec:
  interval: 1h
  chart:
    spec:
      chart: forgejo
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: forgejo
        namespace: forgejo
  values: {}
