apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
  namespace: gatus
spec:
  values:
    # service:
    #   annotations:
    #     tailscale.com/expose: "true"
    #     tailscale.com/hostname: "gatus"

    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - status.simplelumine.com
      tls:
        - secretName: gatus-tls
          hosts:
            - status.simplelumine.com

    env:
      DATABASE_URL:
        valueFrom:
          secretKeyRef:
            name: gatus-db-secret
            key: DATABASE_URL

    config:
      storage:
        type: postgres
        path: "${DATABASE_URL}"
        caching: true

      endpoints:
        # --- External Services ---
        - name: grafana
          group: external-services
          url: "https://monitor.simplelumine.com"
          interval: 2m
          ui:
            hide-hostname: true
          conditions:
            - "[STATUS] == 200"

        - name: open-webui
          group: external-services
          url: "https://chat.simplelumine.com"
          interval: 2m
          ui:
            hide-hostname: true
          conditions:
            - "[STATUS] == 200"

        - name: gatus
          group: external-services
          url: "https://status.simplelumine.com"
          interval: 2m
          ui:
            hide-hostname: true
          conditions:
            - "[STATUS] == 200"

        - name: litellm
          group: external-services
          url: "https://api.simplelumine.com"
          interval: 2m
          ui:
            hide-hostname: true
          conditions:
            - "[STATUS] == 200"

        - name: coder
          group: external-services
          url: "https://code.simplelumine.com"
          interval: 2m
          ui:
            hide-hostname: true
          conditions:
            - "[STATUS] == 200"

        # --- Textverse Services ---
        - name: sillytavern
          group: textverse-services
          url: "https://st.textverse.top"
          interval: 2m
          ui:
            hide-hostname: true
          conditions:
            - "[STATUS] == 200"

        - name: sillytavern-unitedstates
          group: textverse-services
          url: "https://st-us.textverse.top"
          interval: 2m
          ui:
            hide-hostname: true
          conditions:
            - "[STATUS] == 200"

        - name: sillytavern-hongkong
          group: textverse-services
          url: "https://st-hk.textverse.top"
          interval: 2m
          ui:
            hide-hostname: true
          conditions:
            - "[STATUS] == 200"
