apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
  namespace: gatus
spec:
  values:
    service:
      type: ClusterIP
    persistence:
      enabled: false
    serviceMonitor:
      enabled: false
    resources:
      requests:
        cpu: 50m
        memory: 32Mi

    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - status.simplelumine.dev
      tls:
        - secretName: gatus-tls
          hosts:
            - status.simplelumine.dev

    config:
      endpoints:
        # --- Core System ---
        - name: ZITADEL
          group: SimpleLumine
          url: "https://auth.simplelumine.dev"
          interval: 60s
          conditions:
            - "[STATUS] == 200"

        - name: Grafana
          group: SimpleLumine
          url: "https://monitor.simplelumine.dev"
          interval: 60s
          conditions:
            - "[STATUS] == 200"

        - name: Headlamp
          group: SimpleLumine
          url: "https://k8s.simplelumine.dev"
          interval: 60s
          conditions:
            - "[STATUS] < 500"

        # --- Platform Services ---
        - name: Gatus
          group: SimpleLumine
          url: "https://status.simplelumine.dev"
          interval: 60s
          conditions:
            - "[STATUS] == 200"

        - name: Vaultwarden
          group: SimpleLumine
          url: "https://vault.simplelumine.dev"
          interval: 60s
          conditions:
            - "[STATUS] == 200"

        - name: Coder
          group: SimpleLumine
          url: "https://coder.simplelumine.dev"
          interval: 60s
          conditions:
            - "[STATUS] < 500"

        # --- Applications ---
        - name: Open WebUI
          group: SimpleLumine
          url: "https://chat.simplelumine.dev"
          interval: 60s
          conditions:
            - "[STATUS] == 200"

        - name: Simple Gemini
          group: SimpleLumine
          url: "https://gemini.simplelumine.dev"
          interval: 60s
          conditions:
            - "[STATUS] < 500"

        - name: Ghostfolio
          group: SimpleLumine
          url: "https://invest.simplelumine.dev"
          interval: 60s
          conditions:
            - "[STATUS] == 200"

        # --- Textverse ---
        - name: SillyTavern
          group: Textverse
          url: "https://st.textverse.space"
          interval: 60s
          conditions:
            - "[STATUS] == 200"

        - name: Space Card
          group: Textverse
          url: "https://sc-assets.textverse.space"
          interval: 60s
          conditions:
            - "[STATUS] < 500"
