apiVersion: v1
kind: Secret
metadata:
    name: ghostfolio-secret
    namespace: ghostfolio
type: Opaque
stringData:
    JWT_SECRET_KEY: ENC[AES256_GCM,data:+kJOFLX8hHgShLG6CMPmTl+55av0iobbPUoYFy/ahgcxunMM+8y/6aFlOGTy97kXnck4zWb9CMWI7JIyTNnPNQ==,iv:VXipjgqRsSnBV4xujk5eOSyAqJt7Nl1eBpek1OiqqQs=,tag:l0Upn2HZLudDBQOwMtnlJw==,type:str]
    ACCESS_TOKEN_SALT: ENC[AES256_GCM,data:3ntj164ObEq3KTiYpbQNvIh72nNryowZ/BJ6Ye05N35JG+RzMFaDbv50EVPqIgMl9k+a1hXAN/wAYhVlWeejdQ==,iv:eEGMll+iSqkwwePnpBxURHbPT2FdcftWKLZ/ISZy4xU=,tag:vqtVODBcmnm3hc5DkTY9VQ==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:UkMx9b/BjtfVjZ9b+5vQEw2mVC7zTIZaTyeqJkBoQpfHj0miJ41wLgLhwtOG8Wu1,iv:ZIM/ArG0suDEDvgJVNp51e1Xk0AIVr58GuhQguJaLeQ=,tag:y+tdbCsdZ1+bU1j3yJbUvw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NDEvWmlVemhmZDQwWkhU
            L3FyZXFBV1VDcGhacUl0YmJCWnpBMytXeG1NCkt6YjZyRHlRWjlXWEo2Y0pQZXlO
            dmxKbTZBSW1sNlVBT3VVbi8wdDVaL2MKLS0tIDYrekFGZDV5ZXlJU2UvZEMxeFdB
            ZUo1SDRyL3pXcTArVmQ5SjJTbEdjUVUKTYPS2DNeRuGF5GVjHM4JIKjyoAagCj9e
            oM5HKh2jYuMCQB7SFUWx+1WrDZjE27a8fQ70IwcVJeajN4vNjRiraw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T03:39:53Z"
    mac: ENC[AES256_GCM,data:WcPcLtceHVbyWNfUWywvTpq4XH7i38NaUA+gLKAYhhfwl3btl7UkKFbMdIG39SLO3teEmCnipF9WXkgg/gtWy/ogNpJ+ZSDU4daraHHTyD6JdSKdditQjZvwoZ40W3AK6RE2IRV/XYEZQNtxkAnvqmoZQeB0KTUdWA628NRSLsY=,iv:e40my7FHL+pATumMUWb0EB6mVn8Q7jxX1NlzrMaT6j8=,tag:xzihjunowZbLMZ9Oy8pxGg==,type:str]
    version: 3.13.3
