apiVersion: v1
kind: Secret
metadata:
    name: ghostfolio-secret
    namespace: ghostfolio
type: Opaque
stringData:
    JWT_SECRET_KEY: ENC[AES256_GCM,data:JUW/OEZrE/hDxh2I2GuaaazUAjCZNUj7Hu8XZlpFpNrzzandooeVBOnW1G6TYcIYx/wGr5xNbSexvmaFxL2/vQ==,iv:C000BiinAlabY2iHG9eXf/QFWhoS+LcYYpaPmkYOUWE=,tag:Hw/WDkFCS/qpBdpb0beUnw==,type:str]
    ACCESS_TOKEN_SALT: ENC[AES256_GCM,data:zte6QtPrQW6iGppeo69Ry3Fk/SpOuphs+rvHdCU6+UHsZ0r80aGuwjAWLAxnJvwYwXPKFFiCIVpYpL1GRvcVgw==,iv:S5YScoQH0f5DiVHxgCKk/KEcp0mq+96KDWnVgA1owc0=,tag:tKnRR6oPG1L2MNNyG27hEg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYllQY2pYU1pNNHg5dzdr
            M0QvMUlwL1pIa3Q1T05YUi9nNXhaa2NBRW04CkJHV2U0RjFQTm5peHVNczZlQTgz
            YjNzL1Mva210bHFZU2Z6MElXSlhZVWsKLS0tIExUZnFOM3ZCTXYyNEY2dEhWVHF0
            RUo5R0g4NVNCRUhVdFZoRTdkbHdiOTgKAIaDYDa2qbepBDTIC4hkum0VSdJSYw0h
            D9iMdSdCvnc0GNIiH4I4V28nULyaSqpK/n3anKMnVhm3HGbYOjewSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T03:25:05Z"
    mac: ENC[AES256_GCM,data:qt2jeT74xbmfYhRVz2vbqKlHPuK37KnE/g/xdZz4BfmUePIaQnFlUqSp/qNL4cBVddPzLBOwqADvFG26vVduyLi5bwp2vSYQI7KasUdmD0B0ZhoYq2dPThZlqf4Rs1SJREAHq8VgZSP7ptokmj38B34b2gDKaLTtomIOTYmXiA0=,iv:EjoWtYePwya+Sh/95manUovJLpksm3GSHG4kduc0E2o=,tag:dJ1jICmm6d62nIMVY0sVSA==,type:str]
    version: 3.13.3
