apiVersion: v1
kind: Secret
metadata:
    name: ghostfolio-secret
    namespace: ghostfolio
type: Opaque
stringData:
    JWT_SECRET_KEY: ENC[AES256_GCM,data:+kJOFLX8hHgShLG6CMPmTl+55av0iobbPUoYFy/ahgcxunMM+8y/6aFlOGTy97kXnck4zWb9CMWI7JIyTNnPNQ==,iv:VXipjgqRsSnBV4xujk5eOSyAqJt7Nl1eBpek1OiqqQs=,tag:l0Upn2HZLudDBQOwMtnlJw==,type:str]
    ACCESS_TOKEN_SALT: ENC[AES256_GCM,data:3ntj164ObEq3KTiYpbQNvIh72nNryowZ/BJ6Ye05N35JG+RzMFaDbv50EVPqIgMl9k+a1hXAN/wAYhVlWeejdQ==,iv:eEGMll+iSqkwwePnpBxURHbPT2FdcftWKLZ/ISZy4xU=,tag:vqtVODBcmnm3hc5DkTY9VQ==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:IjvEU6rk/XFk8ZxtZaROmspyncWZ8R4J9HY+1pq1XiaE2SbVCdKGxPChWbFbJqPAY2cpx4o3601EutlpdySiPg==,iv:WCTNmBTt25qtTYscEfGuNADRB01pfJph40XsRNT/1NA=,tag:rwm+7Ui5X8RMBPTW8LTIlQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NDEvWmlVemhmZDQwWkhU
            L3FyZXFBV1VDcGhacUl0YmJCWnpBMytXeG1NCkt6YjZyRHlRWjlXWEo2Y0pQZXlO
            dmxKbTZBSW1sNlVBT3VVbi8wdDVaL2MKLS0tIDYrekFGZDV5ZXlJU2UvZEMxeFdB
            ZUo1SDRyL3pXcTArVmQ5SjJTbEdjUVUKTYPS2DNeRuGF5GVjHM4JIKjyoAagCj9e
            oM5HKh2jYuMCQB7SFUWx+1WrDZjE27a8fQ70IwcVJeajN4vNjRiraw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-22T13:53:14Z"
    mac: ENC[AES256_GCM,data:lOZvsyVS7IJddr3nxVNnCWOlRju2yvlniEJ6Pdby09Fd2olSFqgdcLVKVCW1OQnK0uQcHJUkLIaLQ5AjIdok774g7bF/vdjmLpHvd5SpJ8jGo3dgNyqIqKmFxdh2K+qGMVwg9/Ku/8NSELmfwoHJAVmq9xJKrO+4Hv5t3HOkWv0=,iv:QA/aZYIxAF9xYmvKbyx3DHo3gA4uvFI2O4m92qZrASI=,tag:k6neuh43wMqBSSaPnz7VlQ==,type:str]
    version: 3.13.3
