apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../workloads/ghostfolio
  - ghostfolio-eso.yaml
  - ghostfolio-secret.sops.yaml
  - ingress.yaml

patches:
  - path: ghostfolio-patch.yaml
    target:
      kind: Deployment
      name: ghostfolio
