apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: vaultwarden
type: Opaque
stringData:
    SSO_CLIENT_SECRET: ENC[AES256_GCM,data:tNLv95y2g5wk3c6lqNlNXr2b8+moFt3/+iQLYZhoOG1S4ZiGj+G5P0MiDB6fYaOpRroXxnoGQiMEoR47cfdCXw==,iv:XyYk6nTs21yot1wChRUaL8JzDkNIgMTJpiE+9CZdWCQ=,tag:Cw4iJnUun6ZgBAACvPjS/A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzM2VCS2tkdkVGY0FyVTBq
            SnJRZ2VUZU5OREpWNWFQWDBrSzdXWXFmK2dnCmRDRUVLTGlrQ1R5aEc4SkowbXRE
            ZUtrbFhseHVHKzVGQVFsMFQ1YTF5Q1EKLS0tIHRuZnRXbERJSEZiVi9ZRWd6RGg4
            R21TdzduVmFXeE95ckxyR3NHeWtzaXcKncjxcKSCTqi8nBwwO7FXNrWOW/4SkEgj
            ndn9P88s7D4CrteQbKaanDgCY7GwTjW5E/aPF1y7x+KsnWc+i4ZcsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-23T03:16:07Z"
    mac: ENC[AES256_GCM,data:bgZm1oKSfKl/nqwSdWgifNYrBGL7N1xCuNT57vSXXql3u3GnrsJJoFIXi19NBuqhH1Yg/14BEcvmNtPPFBPpBI7ZjWK0XJmlAXMn2eDGJGOfBMFzHzNoo4SDUERiUQJOGMRnq6ymZqYQO3vhdc8L1PdOemaOXro+o1Dg0UDY4z8=,iv:Zvh1KCJHwRQN3pQ7t+RdGi4GuTAM3PwSO6EW4Tjvo5U=,tag:nMyhCm4/zx5QRadrPZz24Q==,type:str]
    version: 3.13.3
