apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: vaultwarden
type: Opaque
stringData:
    SSO_CLIENT_SECRET: ENC[AES256_GCM,data:qyXxPUBlqq8QLYrqowSZ8Cm/GtN+uWqQBODzyqg7cuLtHXYzJBOwdCYL3ApCWbeWvHHhBVfVTGi4UjcfSwJU8g==,iv:8HXVetd1RRUKFf0ecVdysE+kOezYwrDvn/86SU/E8rE=,tag:FmwI2i9Mkhed1igewr6anA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dUR4U1VIK0VBZkZJVkRJ
            enhoNE45OXdWcFV3bHFnS3Nxc3VLM0xCRVU4CjJlWTF0VTN6V1ArbE0rd2VseG45
            SjBKanlhOE9DMDM1cmlnaWM0VmwzUWcKLS0tIGo0RjFqUUovTE4zeDB0UUVqd2lj
            aHVGb3d2TWN1cGt2K3E3RWVjOWczM00KnDZq7/I3n1wrIj3sruEBa0Y1RlXA/+9K
            3qWBUw9ljfS97X1Bor4da81OAvvRdjlZyTzV1i17adJkAPSv2L6X4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-23T04:40:17Z"
    mac: ENC[AES256_GCM,data:EEyCYGDwQLfYSomES1rt5AR4w0X0r1VhSRRmYpHaD6Qc0BjbMlh4aau+9B00eXggFlKbm2S9f+xAiZYbYjNX7lQ/rFnFmXSWS3nyFJrNRwjCUZWP2Oum6ywQD0P0hXHQ/eoBlEMkqp5+tkjHByg76ET7KI/a8WcJWYzlf6dVHlQ=,iv:npamJjO3HDf2gDPVa6JlcOa3SzSr9IwxR2jfF+wmgAs=,tag:QMiA+eOtLkRlkmULph3+/g==,type:str]
    version: 3.13.3
