apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  template:
    spec:
      containers:
        - name: vaultwarden
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-db-secret
                  key: DATABASE_URL
            - name: DOMAIN
              value: "https://vault.simplelumine.dev"
            - name: SSO_ENABLED
              value: "true"
            - name: SSO_ONLY
              value: "true"
            - name: SIGNUPS_ALLOWED
              value: "true"
            - name: SSO_AUTHORITY
              value: "https://auth.simplelumine.dev"
            - name: SSO_CLIENT_ID
              value: "388732916340884571"
            - name: SSO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-secrets
                  key: SSO_CLIENT_SECRET
            - name: SSO_SCOPES
              value: "openid email profile offline_access"
            - name: SSO_PKCE
              value: "true"
            - name: SSO_AUDIENCE_TRUSTED
              value: ".*"
            # SMTP Configuration (Resend)
            - name: SMTP_HOST
              value: "smtp.resend.com"
            - name: SMTP_PORT
              value: "465"
            - name: SMTP_SECURITY
              value: "force_tls"
            - name: SMTP_FROM
              value: "noreply@simplelumine.dev"
            - name: SMTP_FROM_NAME
              value: "SimpleLumine"
            - name: SMTP_USERNAME
              value: "resend"
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-secrets
                  key: SMTP_PASSWORD
            - name: SMTP_AUTH_MECHANISM
              value: "Plain"
