apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: vaultwarden
type: Opaque
stringData:
    SSO_CLIENT_SECRET: ENC[AES256_GCM,data:qyDQtFFWX8cTJuUfxbE3KoYcTSsV/sWW71FdLIqU6W2EMO0XcOJaqftPERwwHLoODElkImz/p9UXOMHH0B6hcg==,iv:+elveKN5/jSnNknrvF+IB39OXvfE4Yf0TZMz6z34vL8=,tag:3+vWLs8XlfVHx4WmF2veTg==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:RqSc86GLOxy+96FRkjZUqw+/9sMZlsi6nGaSR0uNT2qtyZ8C,iv:a0Gsp8+FhVPbyHVnfATbhpuSspSCsJbjN3a04Ir0Viw=,tag:TfgEpXNIU6ynmT2x3JHKAw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1azVjclJlMk82c2N2Yzls
            S2FDNG8wMDZwQ004alJzQ29PTklocmJ4Z1NZCmV6MWp5UjdKTzhtbEhLT0Z5WTRn
            S1diMTNFVlhLWlYyYTFRYU8wbTNTdmcKLS0tIEpqUldJVXl5Yk9oMEdwZU1wRndj
            K04vL05MMjlVQ1h4UGVhN04vdGdmcm8KckIICFwy+l64UitcBRmELoeN3oRZr72w
            Iw2H173xXFW3A13A50XyQXZRE2xaQzogz98QvTcF5bAWhUMdr+SPbw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-23T05:32:32Z"
    mac: ENC[AES256_GCM,data:5s/Gjraq3cSJ1Z99kO8D6uIAU8AXk9VA6zWkFSYkSiwbZ+fLyGyJyAc//oNZGWMmfO7VcMcwSfGDqELJwEF9lUAQoC874/gU3IVloZLxYepBv7q3GMaGBXRquGvnkQZWgoxP/tvaRYBqaZOU+/zLDcimv6stB2HXsEiTHkSXUZY=,iv:USvU1kQj0QdhqhAI6PEAfQtfzsEleRY40DTEnRXvKTo=,tag:MkAyE8WXOvIDSkXH7K1IhQ==,type:str]
    version: 3.13.3
