apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  values:
    secret:
      existingSecret: "authelia-secret"
    configMap:
      theme: "dark"
      access_control:
        default_policy: bypass
        rules:
          - domain: "gpi.simplelumine.dev"
            resources:
              - "^/ui.*"
            policy: two_factor
      session:
        cookies:
          - domain: "simplelumine.dev"
            subdomain: "auth"
            default_redirection_url: "https://simplelumine.dev"
        expiration: "1 hour"
        inactivity: "5 minutes"
        redis:
          enabled: true
          host: "redis.redis.svc.cluster.local"
          port: 6379
      storage:
        postgres:
          enabled: true
          address: "tcp://postgres-rw.postgres.svc.cluster.local:5432"
          database: "authelia"
          username: "authelia"
      authentication_backend:
        ldap:
          enabled: true
          implementation: "lldap"
          address: "ldap://lldap.lldap.svc.cluster.local:3890"
          base_dn: "dc=simplelumine,dc=dev"
          user: "cn=admin,ou=people,dc=simplelumine,dc=dev"
          password:
            path: "authentication.ldap.password.txt"
      notifier:
        smtp:
          enabled: true
          address: "submissions://smtp.resend.com:465"
          username: "resend"
          sender: "Authelia <auth@simplelumine.dev>"
          password:
            path: "notifier.smtp.password.txt"
