apiVersion: v1
kind: Secret
metadata:
    name: authelia-secret
    namespace: authelia
type: Opaque
stringData:
    jwt_secret: ENC[AES256_GCM,data:FEJt9kVu2+jMo+fCx6n8c/KbghFh/Mw0YqAKutah10E5Bqf3Bg82c3wJyizaTRaGrMMDwLzmvN/Jevms5iymbw==,iv:2drw6mTRztIR8nGeVcPIFVwFZ3q4MxHyJMQi1rJFXjE=,tag:9e/d1sOJKz/bzzu9zEQGGw==,type:str]
    session.secret: ENC[AES256_GCM,data:VPiBk97qcN/XCV1DFeAJusDQEBEjrPqtWQ9DMOMPOE08klnn+VANX5lw2HEg4ywXFHq2je3VXxm3+mspfQQOuw==,iv:a6bXB9Cg+lmc9zKDDYWr+5PZmyn2wip7gwWwZCEryVk=,tag:vTYtpFsxCifOYS22BU7uUA==,type:str]
    storage.encryption_key: ENC[AES256_GCM,data:LysIgSoJsHSNaYuyOEfeKYS1eyI7HkzCpjJyM37qiGFv3NsJ6Tsf6yMRMWXXFFuq8v3Ad90j16CUAP3umwkrww==,iv:JXP+yNiVWI/us3HHQWVVhBr9RpAME0hwITJUA9c23a0=,tag:qMBZiUSs7enF1TBNzQMUjA==,type:str]
    notifier.smtp.password: ENC[AES256_GCM,data:uF6JUao/9DKYR9jmMm0IOA/IzJeqWKwB9FQdsnzkjMXCm4vs,iv:WQSfJpRwNrmrHvkXx34PpO+SMsmM5jr8g46+yFMGBXk=,tag:PYJR2hcKh2bR1Y4rCT0bPA==,type:str]
    authentication.backend.ldap.password: ENC[AES256_GCM,data:5OwVt8jgi6BS311iBIRfQS561cOw0l706DGxPH+6z8U=,iv:YVxU5MUKTz65awE4KfbvWb5hy1WafCvIoQ9nBnSJ1PU=,tag:B6hAlVPCdpt1uS2J3V6tUA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNFl2M1o4QStVMmlQYVN0
            eG1TYUtmR3ZCcVJISTZzbGdHQS9XOXh5MEdRCjgxMThaVUpCWnY5RnFGcm9LUjFk
            Rkg0OXdZdS91OG9hL3pUNUw4RDAzdTAKLS0tIHlvRjFWczMzZWphN2lJaHcyd0Q5
            c3dvcFpCZGJ5TUlmMW5yVENlbTI0cG8KOgxpwWoWCk9f27+3dT5+kMbIEdTGlDqg
            gvXUf/0+/dhpVJb+3kh7HSrzTkpUx73gfzGkM2ZD5Kkb7chuYNfvew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T19:55:53Z"
    mac: ENC[AES256_GCM,data:RdMjqVYITWRtvqkIMjIafhhe3cz01WNCdk9f0spy6matgyS/uZvpBbgS28+xG6IiQUEX9vCgV++VPUm2lc77FYh/lLnmzgJxYSVszzmgfljmSHVXnyQakLgHU/FmPobinXQIQi8p+AV77ZlaShVWdEcjoCxF7KQnPV+KvZQ6M70=,iv:7oekiioWJ7lyZRIkZzsr06G5FAw7N2GYqAxyp3XIq+E=,tag:gsx5CJ4ZGh/rDxp5O/W3Pg==,type:str]
    version: 3.13.3
