apiVersion: v1
kind: Secret
metadata:
    name: authelia-secret
    namespace: authelia
type: Opaque
stringData:
    identity_validation.reset_password.jwt.hmac.key: ENC[AES256_GCM,data:+5+zcZ17ZEXEMcDN9cXRDnKLlImEh+ZRiTEe5lSFrepUOgOti9HBglhYiR97eT9z1YfV5Clb4UFZLadRiNUvAw==,iv:4f4BmtxSlapkJFrQKEh8mdgBJJX1Yabv7MM9Hv+YDt8=,tag:/c3iWa02iAvO/Z5TA07FOw==,type:str]
    session.encryption.key: ENC[AES256_GCM,data:2dmzmOiIcAVvwBvEfMsHhTl2R/38RgbYTRX0CSWes2y9ajSc526YEGDwrByQvcuNZZ80YyQ6IQ142kwHWK2MQA==,iv:T+1Fv0xSC84yNjEY6lX4rDD/5Jeu6hw8brPOIuC9468=,tag:pLXaFuGSojB9iqkq0rrqyQ==,type:str]
    storage.encryption.key: ENC[AES256_GCM,data:YaswPHkyX0udv1q2IjfEzHy37U8tdpaXAMCmf2AO6uiAAXoF+3zHMx0OxZcmMBVrhVVTMceFYRPxQm0InzRUKA==,iv:Z5tyen9/ls5PSbz2GFNbtLOz0aMXNwOyxFHBHf8WVUE=,tag:G5C9yCMVWB6wgrG71ySzZg==,type:str]
    notifier.smtp.password.txt: ENC[AES256_GCM,data:EYxw6x6d5Hs3lKXlZtZ71wBDQEheYBep2ONeNUYAsReAv1iL,iv:cGCOVcrJU8+AwyuM9X2D/I5U6i3rsBZk8fkgV/NOJFI=,tag:17eLmsf/MesHLeYYVc266Q==,type:str]
    authentication.ldap.password.txt: ENC[AES256_GCM,data:RcNBLqrjOJnRRWIPL6nX8yyEx7kKEoIs6ybkRIIOU/g=,iv:LgF2uVK+smbbxRiu77Hhb13chGB6/ZKiOT3DTCwHr34=,tag:XiBMCH/vImSUNK04tsGJ1A==,type:str]
    session.redis.password.txt: ""
    storage.postgres.password.txt: ENC[AES256_GCM,data:TDD2CndBZMfgZj4Aj+8xuw==,iv:NCBdhOWVX2PoJKrcUso86UEmjj8Hms9bT2xZEA4n0co=,tag:ZV3/ohFWjAWjM4pLspmYMQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZVhXWlJYT3ova3hxMXFi
            QnhFQXZvM3VMSDJPc0tYZExxUUEvSFlXdUNRCktZRE5GcHV4RDNCU2cxdjVXaDVI
            VnorVDBiQXdjblVJMmRpRHhvb2RqNWsKLS0tIE1Vd0RJUmVvT3AvK0FxTXVOUm93
            TEpJcVU3ZU9RRWh5ajg0WHgzZGUrblkKgI5gD6/uT6/fI8ic4G30nQD7ztLHK7bd
            kqSsWCmaygGw5ulUemrdDuJeXsfhme59WNY1ZKIEoqKi4fdCMkpIyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T20:34:01Z"
    mac: ENC[AES256_GCM,data:ACZsvKJRdMz8cDls8QfWHO5S4SirfFPp3tGEiBRXODklok/hZDmjhEza7PsLFRcfotsLJ9QTh57egHYlllWgMZLJCWDtePjfEfIk5Vv4O9VInBAhARLULQLd4N43wH76MSv+yR46Hfu4LcVoggdgemA+VYlTk7VK0Zz7AXGiqAg=,iv:GVvwpNXEo1ZqzvjNhm9qwA5vtjKWYES+xqllOyU0xIY=,tag:FMnf+N+hjUVYTvZPxnArNA==,type:str]
    version: 3.13.3
