apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-db-secret-sync
  namespace: authelia
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: postgres-store
    kind: ClusterSecretStore
  target:
    name: authelia-db-secret
    template:
      engineVersion: v2
      data:
        AUTHELIA_STORAGE_POSTGRES_PASSWORD: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: authelia-db-secret
        property: password
