apiVersion: v1
kind: Secret
metadata:
    name: authelia-secret
    namespace: authelia
type: Opaque
stringData:
    identity_validation.reset_password.jwt.hmac.key: ENC[AES256_GCM,data:91kVTar2StbSSSgS37NJ4WBZ+/kxHPZiOygpyaLUntSkr1kAajCYLBraX79tNCTxxkTTgk3LEWpgZSlOsmFVtw==,iv:lImXtUiBXJudxoPLvE+9igRgBJRNgzrHxs2SZJObXzA=,tag:HC70eOzf9q3mx4PXKiJc7A==,type:str]
    session.encryption.key: ENC[AES256_GCM,data:wzLS24LX0PDTVjV5CAYmzmV3fTSW2f0WRoVSoQ40abdbK0V43DrsTlg4JpwrXe2MOh9FvIDYIKl+AekPzhxrRw==,iv:TXOiGn1JafCnKD9zuCOMyeQZ4tgMmqIao29Fv4xd/6M=,tag:Q3qoVswSyMe+KKmXT+z1cw==,type:str]
    storage.encryption.key: ENC[AES256_GCM,data:VLXrUmDcII0uoeyVqfV/VVK1/t1U48+v5rpGb7IQifrjczUE4eLLfDbgpgckji1t4yhxhfNiGW+1x7E3aszygA==,iv:sH4YnBsfeKfFILnXK+lR4JIBHoytiBMGCFEkmkOmjgY=,tag:xwMxo2i8hyx4uQDb4DECNw==,type:str]
    notifier.smtp.password.txt: ENC[AES256_GCM,data:D56TMPCNh8SRY9a/vVKWnUi9JrzDVzHTXKwY+Hqb0gb1ZqBk,iv:LtsV+Y6ltKrdEe9shmzZY43qrRz5qO8R4r4aWmsoXyE=,tag:DiBCzYVZDbsl8rt6wGMNNw==,type:str]
    authentication.ldap.password.txt: ENC[AES256_GCM,data:TAlwZDoREtmIojnruZaluStI4+33i/aN6i9Q1a+sJgk=,iv:gi0zeDlCdG2hA2hVf5F7G30EFC7pNqnjC/1uKFYUIrU=,tag:Rpsa6/elHcoGb8PpU/t/Iw==,type:str]
    session.redis.password.txt: ""
    storage.postgres.password.txt: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdkRidlNVUWNjOFBKcEdz
            RDcwS1RsRUhzSDE5KzlzRlV1cXVrYWJsRlZzCm5iWjRQQWJjYVFMcG5pTTc5SVky
            QkRYYlBOZVdJYjNVSE9Wd0l3anp3VGMKLS0tIGNuK0prd2F0di9wMmZzYmxpQ2hh
            TWRwWlZ2RDlCT1hncDMrbWxkQTM5SDAKqrpi7x0jtmHH5trgKHwd1C/oDzBjd3qe
            7pXeoRQdnK3QtFxHCz9orsJMxW0NeMjlohVQEvHxW/sLjVGR53cGug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhr8f8ze9ymr9cu9kmkw5w7feg6e5lae7ggjug4e5x87fukudydspd0fpx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T20:23:19Z"
    mac: ENC[AES256_GCM,data:Vm+pK+OkT9EfbrtFHVfcl9bGbAy0Qu1uw3xNLqa1h8anfoL24YWsHRaRAIaAO9pD0PnarcK9/wsQ4FD+x6BDrQO5z1r4BqysoLTHjrGMNXr8X1Hn8R50G9JDZ5hC7h+Gdh7sb185+zDXNwhSapAfXQvgJV5FottNyarl741P/8s=,iv:qGcAtB4UHiXhdS/RgNNnn8p5aMuoaCo/1WRaHHmUIkY=,tag:jqhY2bghaRXwToisK90Yrg==,type:str]
    version: 3.13.3
